-- Lumen UI: library + demo in one file. Paste the whole thing into your executor.
local Lumen = (function()
-- Lumen UI single-file bundle (generated by tools/bundle.py, do not edit by hand)
local Node = {}
-- anything that isn't a real field (Name / Parent) is looked up as a child,
-- which is what makes `script.Parent.Util.Create` work
Node.__index = function(self, key)
	return rawget(self, "_children")[key]
end

local function newNode(name, parent)
	local node = setmetatable({ Name = name, Parent = parent, _children = {} }, Node)
	if parent then
		parent._children[name] = node
	end
	return node
end

local sources = {}
local cache = {}

local function fakeRequire(node)
	if cache[node] == nil then
		cache[node] = sources[node](node, fakeRequire)
	end
	return cache[node]
end

local n_root = newNode("LumenUI")
local n_Components = newNode("Components", n_root)
local n_Core = newNode("Core", n_root)
local n_Theme = newNode("Theme", n_root)
local n_Util = newNode("Util", n_root)
local n_Components_Button = newNode("Button", n_Components)
local n_Components_Dropdown = newNode("Dropdown", n_Components)
local n_Components_Label = newNode("Label", n_Components)
local n_Components_Slider = newNode("Slider", n_Components)
local n_Components_TextBox = newNode("TextBox", n_Components)
local n_Components_Toggle = newNode("Toggle", n_Components)
local n_Core_Container = newNode("Container", n_Core)
local n_Core_Notification = newNode("Notification", n_Core)
local n_Core_Section = newNode("Section", n_Core)
local n_Core_Tab = newNode("Tab", n_Core)
local n_Core_Window = newNode("Window", n_Core)
local n_Util_Create = newNode("Create", n_Util)
local n_Util_Signal = newNode("Signal", n_Util)
local n_Util_Tween = newNode("Tween", n_Util)

-- Components/Button
sources[n_Components_Button] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)
local Signal = require(script.Parent.Parent.Util.Signal)
local Tween = require(script.Parent.Parent.Util.Tween)

local Button = {}
Button.__index = Button

function Button.new(parent, theme, options)
	local self = setmetatable({}, Button)
	self.Clicked = Signal.new()

	local button = Create("TextButton", {
		Name = "Button",
		Size = UDim2.new(1, 0, 0, 36),
		BackgroundColor3 = theme.Surface,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = options.Name or "Button",
		Font = theme.Font,
		TextSize = theme.TextSize,
		TextColor3 = theme.Text,
		Parent = parent,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
	})

	self.Instance = button

	button.MouseEnter:Connect(function()
		Tween.to(button, { BackgroundColor3 = theme.SurfaceHover }, 0.12)
	end)

	button.MouseLeave:Connect(function()
		Tween.to(button, { BackgroundColor3 = theme.Surface }, 0.12)
	end)

	button.MouseButton1Down:Connect(function()
		Tween.to(button, { BackgroundColor3 = theme.Accent }, 0.08)
	end)

	button.MouseButton1Up:Connect(function()
		Tween.to(button, { BackgroundColor3 = theme.SurfaceHover }, 0.12)
	end)

	button.Activated:Connect(function()
		self.Clicked:Fire()
		if options.Callback then
			task.spawn(options.Callback)
		end
	end)

	return self
end

function Button:SetText(text: string)
	self.Instance.Text = text
end

function Button:Destroy()
	self.Clicked:Destroy()
	self.Instance:Destroy()
end

return Button
end

-- Components/Dropdown
sources[n_Components_Dropdown] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)
local Signal = require(script.Parent.Parent.Util.Signal)
local Tween = require(script.Parent.Parent.Util.Tween)

local Dropdown = {}
Dropdown.__index = Dropdown

function Dropdown.new(parent, theme, options)
	local self = setmetatable({}, Dropdown)
	self.Changed = Signal.new()

	self._theme = theme
	self._callback = options.Callback
	self._options = options.Options or {}
	self._selected = options.Default
	self._open = false

	-- root grows when the list opens, which pushes everything below it down
	local root = Create("Frame", {
		Name = "Dropdown",
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		Parent = parent,
	}, {
		Create("UIListLayout", {
			Padding = UDim.new(0, 4),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})

	local header = Create("TextButton", {
		Name = "Header",
		LayoutOrder = 1,
		Size = UDim2.new(1, 0, 0, 36),
		BackgroundColor3 = theme.Surface,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = "",
		Parent = root,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIPadding", {
			PaddingLeft = UDim.new(0, 12),
			PaddingRight = UDim.new(0, 12),
		}),
		Create("TextLabel", {
			Name = "Title",
			Size = UDim2.new(0.5, 0, 1, 0),
			BackgroundTransparency = 1,
			Text = options.Name or "Dropdown",
			Font = theme.Font,
			TextSize = theme.TextSize,
			TextColor3 = theme.Text,
			TextXAlignment = Enum.TextXAlignment.Left,
		}),
	})

	self._valueLabel = Create("TextLabel", {
		Name = "Value",
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.new(1, -20, 0, 0),
		Size = UDim2.new(0.5, -20, 1, 0),
		BackgroundTransparency = 1,
		Font = theme.Font,
		TextSize = theme.TextSize,
		TextColor3 = theme.TextDim,
		TextXAlignment = Enum.TextXAlignment.Right,
		TextTruncate = Enum.TextTruncate.AtEnd,
		Parent = header,
	})

	-- a plain ">" rotated 90 degrees: points down when closed, up when open
	self._arrow = Create("TextLabel", {
		Name = "Arrow",
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.fromScale(1, 0.5),
		Size = UDim2.fromOffset(16, 16),
		BackgroundTransparency = 1,
		Text = ">",
		Font = theme.FontBold,
		TextSize = theme.TextSize,
		TextColor3 = theme.TextDim,
		Rotation = 90,
		Parent = header,
	})

	self._list = Create("Frame", {
		Name = "List",
		LayoutOrder = 2,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundColor3 = theme.Surface,
		BorderSizePixel = 0,
		Visible = false,
		Parent = root,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIPadding", {
			PaddingTop = UDim.new(0, 4),
			PaddingBottom = UDim.new(0, 4),
			PaddingLeft = UDim.new(0, 4),
			PaddingRight = UDim.new(0, 4),
		}),
		Create("UIListLayout", {
			Padding = UDim.new(0, 2),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})

	self.Instance = root

	header.MouseEnter:Connect(function()
		Tween.to(header, { BackgroundColor3 = theme.SurfaceHover }, 0.12)
	end)
	header.MouseLeave:Connect(function()
		Tween.to(header, { BackgroundColor3 = theme.Surface }, 0.12)
	end)
	header.Activated:Connect(function()
		self:_setOpen(not self._open)
	end)

	self:_buildOptions()
	self:_updateLabel()
	return self
end

function Dropdown:_setOpen(open: boolean)
	self._open = open
	self._list.Visible = open
	Tween.to(self._arrow, { Rotation = open and -90 or 90 }, 0.15)
end

function Dropdown:_updateLabel()
	self._valueLabel.Text = self._selected ~= nil and tostring(self._selected) or "Select..."
end

function Dropdown:_buildOptions()
	local theme = self._theme

	-- wipe the old buttons, but keep the layout / padding / corner objects
	for _, child in self._list:GetChildren() do
		if child:IsA("TextButton") then
			child:Destroy()
		end
	end

	for index, option in self._options do
		local isSelected = option == self._selected

		local item = Create("TextButton", {
			Name = tostring(option),
			LayoutOrder = index,
			Size = UDim2.new(1, 0, 0, 28),
			BackgroundColor3 = theme.SurfaceHover,
			BackgroundTransparency = isSelected and 0 or 1,
			BorderSizePixel = 0,
			AutoButtonColor = false,
			Text = tostring(option),
			Font = theme.Font,
			TextSize = theme.TextSize,
			TextColor3 = isSelected and theme.Accent or theme.Text,
			Parent = self._list,
		}, {
			Create("UICorner", { CornerRadius = UDim.new(0, 4) }),
		})

		item.MouseEnter:Connect(function()
			if option ~= self._selected then
				Tween.to(item, { BackgroundTransparency = 0.5 }, 0.1)
			end
		end)
		item.MouseLeave:Connect(function()
			if option ~= self._selected then
				Tween.to(item, { BackgroundTransparency = 1 }, 0.1)
			end
		end)
		item.Activated:Connect(function()
			self:Set(option)
			self:_setOpen(false)
		end)
	end
end

function Dropdown:Set(option, silent: boolean?)
	if option == self._selected then
		return
	end

	self._selected = option
	self:_updateLabel()
	self:_buildOptions()

	if not silent then
		self.Changed:Fire(option)
		if self._callback then
			task.spawn(self._callback, option)
		end
	end
end

function Dropdown:Get()
	return self._selected
end

-- swap out the whole list, e.g. when the player list changes
function Dropdown:Refresh(newOptions: { any })
	self._options = newOptions

	if not table.find(newOptions, self._selected) then
		self._selected = nil
		self:_updateLabel()
	end

	self:_buildOptions()
end

function Dropdown:Destroy()
	self.Changed:Destroy()
	self.Instance:Destroy()
end

return Dropdown
end

-- Components/Label
sources[n_Components_Label] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)

local Label = {}
Label.__index = Label

function Label.new(parent, theme, options)
	local self = setmetatable({}, Label)

	self.Instance = Create("TextLabel", {
		Name = "Label",
		Size = UDim2.new(1, 0, 0, 20),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		Text = options.Text or options.Name or "Label",
		Font = theme.Font,
		TextSize = theme.TextSize,
		TextColor3 = theme.TextDim,
		TextWrapped = true,
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = parent,
	})

	return self
end

function Label:SetText(text: string)
	self.Instance.Text = text
end

function Label:Destroy()
	self.Instance:Destroy()
end

return Label
end

-- Components/Slider
sources[n_Components_Slider] = function(script, require)
local UserInputService = game:GetService("UserInputService")

local Create = require(script.Parent.Parent.Util.Create)
local Signal = require(script.Parent.Parent.Util.Signal)
local Tween = require(script.Parent.Parent.Util.Tween)

local Slider = {}
Slider.__index = Slider

local function isPointer(input: InputObject)
	return input.UserInputType == Enum.UserInputType.MouseButton1
		or input.UserInputType == Enum.UserInputType.Touch
end

function Slider.new(parent, theme, options)
	local self = setmetatable({}, Slider)
	self.Changed = Signal.new()

	self._callback = options.Callback
	self._min = options.Min or 0
	self._max = options.Max or 100
	self._increment = options.Increment or 1
	self._suffix = options.Suffix or ""
	self._value = math.clamp(options.Default or self._min, self._min, self._max)
	self._connections = {}

	local row = Create("Frame", {
		Name = "Slider",
		Size = UDim2.new(1, 0, 0, 50),
		BackgroundColor3 = theme.Surface,
		BorderSizePixel = 0,
		Parent = parent,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIPadding", {
			PaddingLeft = UDim.new(0, 12),
			PaddingRight = UDim.new(0, 12),
		}),
		Create("TextLabel", {
			Name = "Title",
			Position = UDim2.fromOffset(0, 6),
			Size = UDim2.new(0.7, 0, 0, 20),
			BackgroundTransparency = 1,
			Text = options.Name or "Slider",
			Font = theme.Font,
			TextSize = theme.TextSize,
			TextColor3 = theme.Text,
			TextXAlignment = Enum.TextXAlignment.Left,
		}),
	})

	self._valueLabel = Create("TextLabel", {
		Name = "Value",
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.new(1, 0, 0, 6),
		Size = UDim2.new(0.3, 0, 0, 20),
		BackgroundTransparency = 1,
		Font = theme.Font,
		TextSize = theme.TextSize,
		TextColor3 = theme.TextDim,
		TextXAlignment = Enum.TextXAlignment.Right,
		Parent = row,
	})

	-- the hit box is taller than the visible bar so it's easy to grab on mobile
	local hitbox = Create("Frame", {
		Name = "Hitbox",
		AnchorPoint = Vector2.new(0, 1),
		Position = UDim2.new(0, 0, 1, -4),
		Size = UDim2.new(1, 0, 0, 20),
		BackgroundTransparency = 1,
		Parent = row,
	})

	self._track = Create("Frame", {
		Name = "Track",
		AnchorPoint = Vector2.new(0, 0.5),
		Position = UDim2.fromScale(0, 0.5),
		Size = UDim2.new(1, 0, 0, 6),
		BackgroundColor3 = theme.Stroke,
		BorderSizePixel = 0,
		Parent = hitbox,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(1, 0) }),
	})

	self._fill = Create("Frame", {
		Name = "Fill",
		Size = UDim2.fromScale(0, 1),
		BackgroundColor3 = theme.Accent,
		BorderSizePixel = 0,
		Parent = self._track,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(1, 0) }),
	})

	self.Instance = row

	local dragging = false

	local function updateFromX(x: number)
		local width = self._track.AbsoluteSize.X
		if width <= 0 then
			return
		end
		local alpha = math.clamp((x - self._track.AbsolutePosition.X) / width, 0, 1)
		self:Set(self._min + (self._max - self._min) * alpha)
	end

	hitbox.InputBegan:Connect(function(input)
		if isPointer(input) then
			dragging = true
			updateFromX(input.Position.X)
		end
	end)

	table.insert(self._connections, UserInputService.InputChanged:Connect(function(input)
		if not dragging then
			return
		end
		if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
			updateFromX(input.Position.X)
		end
	end))

	table.insert(self._connections, UserInputService.InputEnded:Connect(function(input)
		if isPointer(input) then
			dragging = false
		end
	end))

	self:_render(false)
	return self
end

function Slider:_render(animate: boolean)
	local alpha = (self._value - self._min) / (self._max - self._min)
	local size = UDim2.fromScale(alpha, 1)

	if animate then
		Tween.to(self._fill, { Size = size }, 0.06)
	else
		self._fill.Size = size
	end

	self._valueLabel.Text = tostring(self._value) .. self._suffix
end

function Slider:Set(value: number, silent: boolean?)
	-- snap to the increment, then clamp. The round() cleans up float noise like 0.30000000004
	value = math.floor((value - self._min) / self._increment + 0.5) * self._increment + self._min
	value = math.clamp(math.round(value * 10000) / 10000, self._min, self._max)

	if value == self._value then
		return
	end

	self._value = value
	self:_render(true)

	if not silent then
		self.Changed:Fire(value)
		if self._callback then
			task.spawn(self._callback, value)
		end
	end
end

function Slider:Get(): number
	return self._value
end

function Slider:Destroy()
	for _, connection in self._connections do
		connection:Disconnect()
	end
	self.Changed:Destroy()
	self.Instance:Destroy()
end

return Slider
end

-- Components/TextBox
sources[n_Components_TextBox] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)
local Signal = require(script.Parent.Parent.Util.Signal)
local Tween = require(script.Parent.Parent.Util.Tween)

local TextBox = {}
TextBox.__index = TextBox

function TextBox.new(parent, theme, options)
	local self = setmetatable({}, TextBox)
	self.Changed = Signal.new()
	self._callback = options.Callback

	local row = Create("Frame", {
		Name = "TextBox",
		Size = UDim2.new(1, 0, 0, 36),
		BackgroundColor3 = theme.Surface,
		BorderSizePixel = 0,
		Parent = parent,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIPadding", {
			PaddingLeft = UDim.new(0, 12),
			PaddingRight = UDim.new(0, 8),
		}),
		Create("TextLabel", {
			Name = "Title",
			Size = UDim2.fromScale(0.5, 1),
			BackgroundTransparency = 1,
			Text = options.Name or "TextBox",
			Font = theme.Font,
			TextSize = theme.TextSize,
			TextColor3 = theme.Text,
			TextXAlignment = Enum.TextXAlignment.Left,
		}),
	})

	local stroke = Create("UIStroke", {
		Color = theme.Stroke,
		Thickness = 1,
	})

	self._box = Create("TextBox", {
		Name = "Input",
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.fromScale(1, 0.5),
		Size = UDim2.new(0.5, 0, 0, 24),
		BackgroundColor3 = theme.Background,
		BorderSizePixel = 0,
		Text = options.Default or "",
		PlaceholderText = options.Placeholder or "Type here...",
		PlaceholderColor3 = theme.TextDim,
		ClearTextOnFocus = options.ClearOnFocus == true,
		Font = theme.Font,
		TextSize = theme.TextSize - 1,
		TextColor3 = theme.Text,
		TextTruncate = Enum.TextTruncate.AtEnd,
		Parent = row,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(0, 4) }),
		Create("UIPadding", {
			PaddingLeft = UDim.new(0, 6),
			PaddingRight = UDim.new(0, 6),
		}),
		stroke,
	})

	self.Instance = row

	self._box.Focused:Connect(function()
		Tween.to(stroke, { Color = theme.Accent }, 0.12)
	end)

	self._box.FocusLost:Connect(function(enterPressed)
		Tween.to(stroke, { Color = theme.Stroke }, 0.12)

		local text = self._box.Text
		self.Changed:Fire(text, enterPressed)
		if self._callback then
			task.spawn(self._callback, text, enterPressed)
		end
	end)

	return self
end

function TextBox:Set(text: string)
	self._box.Text = text
end

function TextBox:Get(): string
	return self._box.Text
end

function TextBox:Destroy()
	self.Changed:Destroy()
	self.Instance:Destroy()
end

return TextBox
end

-- Components/Toggle
sources[n_Components_Toggle] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)
local Signal = require(script.Parent.Parent.Util.Signal)
local Tween = require(script.Parent.Parent.Util.Tween)

local Toggle = {}
Toggle.__index = Toggle

local KNOB_OFF = UDim2.new(0, 3, 0.5, 0)
local KNOB_ON = UDim2.new(1, -17, 0.5, 0)

function Toggle.new(parent, theme, options)
	local self = setmetatable({}, Toggle)
	self.Changed = Signal.new()

	self._theme = theme
	self._callback = options.Callback
	self._value = options.Default == true

	local row = Create("TextButton", {
		Name = "Toggle",
		Size = UDim2.new(1, 0, 0, 36),
		BackgroundColor3 = theme.Surface,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = "",
		Parent = parent,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIPadding", {
			PaddingLeft = UDim.new(0, 12),
			PaddingRight = UDim.new(0, 12),
		}),
		Create("TextLabel", {
			Name = "Title",
			Size = UDim2.new(1, -50, 1, 0),
			BackgroundTransparency = 1,
			Text = options.Name or "Toggle",
			Font = theme.Font,
			TextSize = theme.TextSize,
			TextColor3 = theme.Text,
			TextXAlignment = Enum.TextXAlignment.Left,
		}),
	})

	self._track = Create("Frame", {
		Name = "Track",
		Size = UDim2.fromOffset(38, 20),
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.fromScale(1, 0.5),
		BackgroundColor3 = theme.Stroke,
		BorderSizePixel = 0,
		Parent = row,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(1, 0) }),
	})

	self._knob = Create("Frame", {
		Name = "Knob",
		Size = UDim2.fromOffset(14, 14),
		AnchorPoint = Vector2.new(0, 0.5),
		Position = KNOB_OFF,
		BackgroundColor3 = theme.Text,
		BorderSizePixel = 0,
		Parent = self._track,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(1, 0) }),
	})

	self.Instance = row

	row.MouseEnter:Connect(function()
		Tween.to(row, { BackgroundColor3 = theme.SurfaceHover }, 0.12)
	end)
	row.MouseLeave:Connect(function()
		Tween.to(row, { BackgroundColor3 = theme.Surface }, 0.12)
	end)
	row.Activated:Connect(function()
		self:Set(not self._value)
	end)

	self:_render(false)
	return self
end

function Toggle:_render(animate: boolean)
	local on = self._value
	local trackGoal = { BackgroundColor3 = on and self._theme.Accent or self._theme.Stroke }
	local knobGoal = { Position = on and KNOB_ON or KNOB_OFF }

	if animate then
		Tween.to(self._track, trackGoal, 0.15)
		Tween.to(self._knob, knobGoal, 0.15)
	else
		self._track.BackgroundColor3 = trackGoal.BackgroundColor3
		self._knob.Position = knobGoal.Position
	end
end

-- silent = true skips the callback / Changed signal (handy when loading configs)
function Toggle:Set(value: boolean, silent: boolean?)
	value = not not value
	if value == self._value then
		return
	end

	self._value = value
	self:_render(true)

	if not silent then
		self.Changed:Fire(value)
		if self._callback then
			task.spawn(self._callback, value)
		end
	end
end

function Toggle:Get(): boolean
	return self._value
end

function Toggle:Destroy()
	self.Changed:Destroy()
	self.Instance:Destroy()
end

return Toggle
end

-- Components
sources[n_Components] = function(script, require)
-- One place that lists every component. Container.luau loops over this table and
-- generates the AddButton / AddToggle / ... methods automatically, so adding a new
-- component is just: write the file, add one line here.

return {
	Label = require(script.Label),
	Button = require(script.Button),
	Toggle = require(script.Toggle),
	Slider = require(script.Slider),
	TextBox = require(script.TextBox),
	Dropdown = require(script.Dropdown),
}
end

-- Core/Container
sources[n_Core_Container] = function(script, require)
-- Both Tabs and Sections can hold components. Instead of copy/pasting the same
-- AddButton/AddToggle/... methods into each one, we bolt them on with this mixin.
--
-- The class needs to have two fields:
--   self._content  -> the Instance that components get parented to
--   self._theme    -> the theme table

local Components = require(script.Parent.Parent.Components)

local Container = {}

function Container.mixin(class)
	for name, constructor in Components do
		class["Add" .. name] = function(self, options)
			return constructor.new(self._content, self._theme, options or {})
		end
	end
end

return Container
end

-- Core/Notification
sources[n_Core_Notification] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)
local Tween = require(script.Parent.Parent.Util.Tween)

local Notification = {}
Notification.__index = Notification

function Notification.new(gui: ScreenGui, theme)
	local self = setmetatable({}, Notification)
	self._theme = theme

	self._holder = Create("Frame", {
		Name = "Notifications",
		AnchorPoint = Vector2.new(1, 1),
		Position = UDim2.new(1, -16, 1, -16),
		Size = UDim2.new(0, 300, 1, -32),
		BackgroundTransparency = 1,
		Parent = gui,
	}, {
		Create("UIListLayout", {
			Padding = UDim.new(0, 8),
			SortOrder = Enum.SortOrder.LayoutOrder,
			VerticalAlignment = Enum.VerticalAlignment.Bottom,
		}),
	})

	return self
end

function Notification:Push(options)
	local theme = self._theme
	local duration = options.Duration or 4

	-- CanvasGroup lets us fade the whole card (text, stroke and all) with one property
	local card = Create("CanvasGroup", {
		Name = "Notification",
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundColor3 = theme.Surface,
		BorderSizePixel = 0,
		GroupTransparency = 1,
		Parent = self._holder,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIStroke", { Color = theme.Stroke, Thickness = 1 }),
		Create("UIPadding", {
			PaddingTop = UDim.new(0, 10),
			PaddingBottom = UDim.new(0, 10),
			PaddingLeft = UDim.new(0, 14),
			PaddingRight = UDim.new(0, 14),
		}),
		Create("UIListLayout", {
			Padding = UDim.new(0, 2),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
		Create("TextLabel", {
			Name = "Title",
			LayoutOrder = 1,
			Size = UDim2.new(1, 0, 0, 18),
			BackgroundTransparency = 1,
			Text = options.Title or "Notice",
			Font = theme.FontBold,
			TextSize = theme.TextSize,
			TextColor3 = theme.Accent,
			TextXAlignment = Enum.TextXAlignment.Left,
		}),
		Create("TextLabel", {
			Name = "Body",
			LayoutOrder = 2,
			Size = UDim2.new(1, 0, 0, 0),
			AutomaticSize = Enum.AutomaticSize.Y,
			BackgroundTransparency = 1,
			Text = options.Content or "",
			Font = theme.Font,
			TextSize = theme.TextSize - 1,
			TextColor3 = theme.Text,
			TextWrapped = true,
			TextXAlignment = Enum.TextXAlignment.Left,
		}),
	})

	Tween.to(card, { GroupTransparency = 0 }, 0.25)

	task.delay(duration, function()
		if not card.Parent then
			return -- window was destroyed in the meantime
		end
		Tween.to(card, { GroupTransparency = 1 }, 0.3).Completed:Wait()
		card:Destroy()
	end)
end

return Notification
end

-- Core/Section
sources[n_Core_Section] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)
local Container = require(script.Parent.Container)

local Section = {}
Section.__index = Section

function Section.new(parent, theme, title: string)
	local self = setmetatable({}, Section)
	self._theme = theme

	self.Instance = Create("Frame", {
		Name = "Section",
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		Parent = parent,
	}, {
		Create("UIListLayout", {
			Padding = UDim.new(0, 6),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
		Create("TextLabel", {
			Name = "Title",
			LayoutOrder = 1,
			Size = UDim2.new(1, 0, 0, 16),
			BackgroundTransparency = 1,
			Text = string.upper(title or "Section"),
			Font = theme.FontBold,
			TextSize = theme.TextSize - 3,
			TextColor3 = theme.TextDim,
			TextXAlignment = Enum.TextXAlignment.Left,
		}),
	})

	self._content = Create("Frame", {
		Name = "Content",
		LayoutOrder = 2,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundColor3 = theme.Section,
		BorderSizePixel = 0,
		Parent = self.Instance,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIStroke", { Color = theme.Stroke, Thickness = 1 }),
		Create("UIPadding", {
			PaddingTop = UDim.new(0, 8),
			PaddingBottom = UDim.new(0, 8),
			PaddingLeft = UDim.new(0, 8),
			PaddingRight = UDim.new(0, 8),
		}),
		Create("UIListLayout", {
			Padding = UDim.new(0, 6),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})

	return self
end

function Section:Destroy()
	self.Instance:Destroy()
end

Container.mixin(Section)

return Section
end

-- Core/Tab
sources[n_Core_Tab] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)
local Tween = require(script.Parent.Parent.Util.Tween)
local Container = require(script.Parent.Container)
local Section = require(script.Parent.Section)

local Tab = {}
Tab.__index = Tab

function Tab.new(window, name: string)
	local self = setmetatable({}, Tab)
	local theme = window.Theme

	self.Name = name
	self._window = window
	self._theme = theme

	self._button = Create("TextButton", {
		Name = name,
		Size = UDim2.new(1, 0, 0, 32),
		BackgroundColor3 = theme.Surface,
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = name,
		Font = theme.Font,
		TextSize = theme.TextSize,
		TextColor3 = theme.TextDim,
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = window.TabList,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIPadding", { PaddingLeft = UDim.new(0, 10) }),
	})

	-- _content is where the Container mixin drops new components
	self._content = Create("ScrollingFrame", {
		Name = name,
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		ScrollBarThickness = 3,
		ScrollBarImageColor3 = theme.Stroke,
		CanvasSize = UDim2.new(),
		AutomaticCanvasSize = Enum.AutomaticSize.Y,
		Visible = false,
		Parent = window.Pages,
	}, {
		Create("UIPadding", {
			PaddingTop = UDim.new(0, 12),
			PaddingBottom = UDim.new(0, 12),
			PaddingLeft = UDim.new(0, 12),
			PaddingRight = UDim.new(0, 14),
		}),
		Create("UIListLayout", {
			Padding = UDim.new(0, 10),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})

	self._button.Activated:Connect(function()
		self:Select()
	end)

	return self
end

function Tab:Select()
	self._window:_selectTab(self)
end

-- called by the window, not meant to be used directly
function Tab:_setActive(active: boolean)
	local theme = self._theme
	self._content.Visible = active

	Tween.to(self._button, {
		BackgroundTransparency = active and 0 or 1,
		TextColor3 = active and theme.Text or theme.TextDim,
	}, 0.15)
end

function Tab:AddSection(title: string)
	return Section.new(self._content, self._theme, title)
end

function Tab:Destroy()
	self._button:Destroy()
	self._content:Destroy()
end

Container.mixin(Tab)

return Tab
end

-- Core/Window
sources[n_Core_Window] = function(script, require)
local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")

local Create = require(script.Parent.Parent.Util.Create)
local Theme = require(script.Parent.Parent.Theme)
local Tab = require(script.Parent.Tab)
local Notification = require(script.Parent.Notification)

local Window = {}
Window.__index = Window

-- In Studio / normal games this is just PlayerGui. If the environment offers gethui()
-- (most executors do) we use that instead, since PlayerGui can get wiped on respawn
-- or inspected by the game.
local function getDefaultParent()
	local ok, hidden = pcall(function()
		return gethui and gethui()
	end)
	if ok and hidden then
		return hidden
	end
	return Players.LocalPlayer:WaitForChild("PlayerGui")
end

local TOPBAR_HEIGHT = 40
local SIDEBAR_WIDTH = 140

function Window.new(options)
	options = options or {}

	local self = setmetatable({}, Window)
	self.Theme = Theme.extend(Theme.Dark, options.Theme)
	self.Tabs = {}

	self._connections = {}
	self._activeTab = nil
	self._toggleKey = options.ToggleKey or Enum.KeyCode.RightShift

	local theme = self.Theme
	local parent = options.Parent or getDefaultParent()

	self.Gui = Create("ScreenGui", {
		Name = "LumenUI",
		ResetOnSpawn = false,
		ZIndexBehavior = Enum.ZIndexBehavior.Sibling,
		DisplayOrder = 100,
		Parent = parent,
	})

	self.Main = Create("Frame", {
		Name = "Main",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.5),
		Size = options.Size or UDim2.fromOffset(580, 400),
		BackgroundColor3 = theme.Background,
		BorderSizePixel = 0,
		Parent = self.Gui,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(0, 10) }),
		Create("UIStroke", { Color = theme.Stroke, Thickness = 1 }),
	})

	-- top bar (also the drag handle)
	local topBar = Create("Frame", {
		Name = "TopBar",
		Size = UDim2.new(1, 0, 0, TOPBAR_HEIGHT),
		BackgroundTransparency = 1,
		Parent = self.Main,
	}, {
		Create("TextLabel", {
			Name = "Title",
			Position = UDim2.fromOffset(14, 0),
			Size = UDim2.new(1, -60, 1, 0),
			BackgroundTransparency = 1,
			Text = options.Title or "Lumen UI",
			Font = theme.FontBold,
			TextSize = theme.TextSize + 1,
			TextColor3 = theme.Text,
			TextXAlignment = Enum.TextXAlignment.Left,
		}),
	})

	local closeButton = Create("TextButton", {
		Name = "Close",
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.new(1, -8, 0.5, 0),
		Size = UDim2.fromOffset(28, 28),
		BackgroundColor3 = theme.Surface,
		BackgroundTransparency = 1,
		AutoButtonColor = false,
		Text = "X",
		Font = theme.FontBold,
		TextSize = theme.TextSize,
		TextColor3 = theme.TextDim,
		Parent = topBar,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
	})

	closeButton.MouseEnter:Connect(function()
		closeButton.BackgroundTransparency = 0
	end)
	closeButton.MouseLeave:Connect(function()
		closeButton.BackgroundTransparency = 1
	end)
	closeButton.Activated:Connect(function()
		self:Destroy()
	end)

	-- thin divider lines
	Create("Frame", {
		Name = "TopDivider",
		Position = UDim2.fromOffset(0, TOPBAR_HEIGHT),
		Size = UDim2.new(1, 0, 0, 1),
		BackgroundColor3 = theme.Stroke,
		BorderSizePixel = 0,
		Parent = self.Main,
	})
	Create("Frame", {
		Name = "SideDivider",
		Position = UDim2.fromOffset(SIDEBAR_WIDTH, TOPBAR_HEIGHT + 1),
		Size = UDim2.new(0, 1, 1, -(TOPBAR_HEIGHT + 1)),
		BackgroundColor3 = theme.Stroke,
		BorderSizePixel = 0,
		Parent = self.Main,
	})

	-- sidebar holds the tab buttons, pages hold the tab content
	self.TabList = Create("Frame", {
		Name = "TabList",
		Position = UDim2.fromOffset(0, TOPBAR_HEIGHT + 1),
		Size = UDim2.new(0, SIDEBAR_WIDTH, 1, -(TOPBAR_HEIGHT + 1)),
		BackgroundTransparency = 1,
		Parent = self.Main,
	}, {
		Create("UIPadding", {
			PaddingTop = UDim.new(0, 8),
			PaddingLeft = UDim.new(0, 8),
			PaddingRight = UDim.new(0, 8),
		}),
		Create("UIListLayout", {
			Padding = UDim.new(0, 4),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})

	self.Pages = Create("Frame", {
		Name = "Pages",
		Position = UDim2.fromOffset(SIDEBAR_WIDTH + 1, TOPBAR_HEIGHT + 1),
		Size = UDim2.new(1, -(SIDEBAR_WIDTH + 1), 1, -(TOPBAR_HEIGHT + 1)),
		BackgroundTransparency = 1,
		ClipsDescendants = true,
		Parent = self.Main,
	})

	self._notifications = Notification.new(self.Gui, theme)

	self:_makeDraggable(topBar)

	table.insert(self._connections, UserInputService.InputBegan:Connect(function(input, gameProcessed)
		if gameProcessed then
			return -- they're typing in chat or a textbox
		end
		if input.KeyCode == self._toggleKey then
			self:Toggle()
		end
	end))

	return self
end

function Window:_makeDraggable(handle: GuiObject)
	local dragging = false
	local dragStart: Vector3
	local startPosition: UDim2

	handle.InputBegan:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
			dragging = true
			dragStart = input.Position
			startPosition = self.Main.Position
		end
	end)

	table.insert(self._connections, UserInputService.InputChanged:Connect(function(input)
		if not dragging then
			return
		end
		if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
			local delta = input.Position - dragStart
			self.Main.Position = UDim2.new(
				startPosition.X.Scale,
				startPosition.X.Offset + delta.X,
				startPosition.Y.Scale,
				startPosition.Y.Offset + delta.Y
			)
		end
	end))

	table.insert(self._connections, UserInputService.InputEnded:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
			dragging = false
		end
	end))
end

function Window:_selectTab(tab)
	if self._activeTab == tab then
		return
	end
	if self._activeTab then
		self._activeTab:_setActive(false)
	end

	self._activeTab = tab
	tab:_setActive(true)
end

function Window:AddTab(name: string)
	local tab = Tab.new(self, name)
	table.insert(self.Tabs, tab)

	-- first tab opens automatically so the window isn't empty
	if #self.Tabs == 1 then
		tab:Select()
	end

	return tab
end

function Window:Notify(options)
	self._notifications:Push(options or {})
end

function Window:SetVisible(visible: boolean)
	self.Main.Visible = visible
end

function Window:Toggle()
	self.Main.Visible = not self.Main.Visible
end

function Window:Destroy()
	for _, connection in self._connections do
		connection:Disconnect()
	end
	table.clear(self._connections)
	self.Gui:Destroy()
end

return Window
end

-- Theme
sources[n_Theme] = function(script, require)
-- All colours and fonts live here so a custom theme is one table away.

local Theme = {}

Theme.Dark = {
	Background = Color3.fromRGB(22, 22, 28),
	Section = Color3.fromRGB(28, 28, 36),
	Surface = Color3.fromRGB(38, 38, 48),
	SurfaceHover = Color3.fromRGB(49, 49, 62),
	Stroke = Color3.fromRGB(58, 58, 72),

	Accent = Color3.fromRGB(94, 129, 244),

	Text = Color3.fromRGB(235, 235, 242),
	TextDim = Color3.fromRGB(150, 150, 168),

	Font = Enum.Font.GothamMedium,
	FontBold = Enum.Font.GothamBold,
	TextSize = 14,

	Corner = UDim.new(0, 6),
}

Theme.Light = {
	Background = Color3.fromRGB(244, 244, 248),
	Section = Color3.fromRGB(236, 236, 242),
	Surface = Color3.fromRGB(255, 255, 255),
	SurfaceHover = Color3.fromRGB(232, 232, 240),
	Stroke = Color3.fromRGB(205, 205, 218),

	Accent = Color3.fromRGB(70, 105, 235),

	Text = Color3.fromRGB(30, 30, 40),
	TextDim = Color3.fromRGB(105, 105, 125),

	Font = Enum.Font.GothamMedium,
	FontBold = Enum.Font.GothamBold,
	TextSize = 14,

	Corner = UDim.new(0, 6),
}

-- Copy a base theme and overwrite whatever the user passed in.
function Theme.extend(base, overrides)
	local result = table.clone(base)
	for key, value in overrides or {} do
		result[key] = value
	end
	return result
end

return Theme
end

-- Util/Create
sources[n_Util_Create] = function(script, require)
-- Tiny helper so we don't have to write Instance.new + 8 property lines every time.
--
--   Create("Frame", { Size = UDim2.fromScale(1, 1) }, {
--       Create("UICorner", { CornerRadius = UDim.new(0, 6) }),
--   })

local function Create(className: string, props: { [string]: any }?, children: { Instance }?): any
	local instance = Instance.new(className)
	local parent

	for key, value in props or {} do
		if key == "Parent" then
			-- set last, it's faster and avoids re-layout while we're still building
			parent = value
		else
			instance[key] = value
		end
	end

	for _, child in children or {} do
		child.Parent = instance
	end

	instance.Parent = parent
	return instance
end

return Create
end

-- Util/Signal
sources[n_Util_Signal] = function(script, require)
-- Minimal signal class. Not as fancy as GoodSignal, but it's tiny and does the job.

local Signal = {}
Signal.__index = Signal

function Signal.new()
	return setmetatable({ _handlers = {} }, Signal)
end

function Signal:Connect(fn)
	local handlers = self._handlers
	local handler = { Fn = fn }
	table.insert(handlers, handler)

	local connection = { Connected = true }

	function connection:Disconnect()
		if not self.Connected then
			return
		end
		self.Connected = false

		local index = table.find(handlers, handler)
		if index then
			table.remove(handlers, index)
		end
	end

	return connection
end

function Signal:Fire(...)
	-- clone first, a handler might disconnect itself while we're looping
	for _, handler in table.clone(self._handlers) do
		task.spawn(handler.Fn, ...)
	end
end

function Signal:Destroy()
	table.clear(self._handlers)
end

return Signal
end

-- Util/Tween
sources[n_Util_Tween] = function(script, require)
local TweenService = game:GetService("TweenService")

local Tween = {}

-- Fire and forget tween. Returns the tween in case you want to wait on it.
function Tween.to(instance: Instance, goal: { [string]: any }, duration: number?, style: Enum.EasingStyle?, direction: Enum.EasingDirection?)
	local info = TweenInfo.new(
		duration or 0.15,
		style or Enum.EasingStyle.Quad,
		direction or Enum.EasingDirection.Out
	)

	local tween = TweenService:Create(instance, info, goal)
	tween:Play()
	return tween
end

return Tween
end

-- init
sources[n_root] = function(script, require)
--[[
	Lumen UI
	A small, modular UI library for Roblox.

	local Lumen = require(ReplicatedStorage.LumenUI)
	local window = Lumen.CreateWindow({ Title = "My Hub" })
	local tab = window:AddTab("Main")
	tab:AddButton({ Name = "Hello", Callback = function() print("hi") end })
]]

local Window = require(script.Core.Window)
local Theme = require(script.Theme)

local Lumen = {}

Lumen.Version = "0.1.0"
Lumen.Themes = Theme

function Lumen.CreateWindow(options)
	return Window.new(options)
end

return Lumen
end

return fakeRequire(n_root)

end)()

-- demo (Lumen is already defined above this line)

local window = Lumen.CreateWindow({
	Title = "Lumen Demo",
	ToggleKey = Enum.KeyCode.RightShift,
})

local main = window:AddTab("Main")

main:AddLabel({ Text = "Tap the X to close. RightShift toggles on keyboards." })

main:AddButton({
	Name = "Say hello",
	Callback = function()
		window:Notify({
			Title = "Hello!",
			Content = "This notification fades out on its own.",
			Duration = 3,
		})
	end,
})

local audio = main:AddSection("Audio")

audio:AddToggle({
	Name = "Enable music",
	Default = true,
	Callback = function(on)
		print("Music:", on)
	end,
})

audio:AddSlider({
	Name = "Volume",
	Min = 0,
	Max = 100,
	Default = 60,
	Increment = 5,
	Suffix = "%",
	Callback = function(value)
		print("Volume:", value)
	end,
})

local settings = window:AddTab("Settings")
local profile = settings:AddSection("Profile")

profile:AddTextBox({
	Name = "Nickname",
	Placeholder = "Enter a name",
	Callback = function(text)
		print("Nickname:", text)
	end,
})

profile:AddDropdown({
	Name = "Quality",
	Options = { "Low", "Medium", "High", "Ultra" },
	Default = "Medium",
	Callback = function(choice)
		print("Quality:", choice)
	end,
})
