-- Lumen UI single-file bundle (generated by tools/bundle.py, do not edit by hand)
local Node = {}
-- anything that isn't a real field (Name / Parent) is looked up as a child,
-- which is what makes `script.Parent.Util.Create` work
Node.__index = function(self, key)
	return rawget(self, "_children")[key]
end

local function newNode(name, parent)
	local node = setmetatable({ Name = name, Parent = parent, _children = {} }, Node)
	if parent then
		parent._children[name] = node
	end
	return node
end

local sources = {}
local cache = {}

local function fakeRequire(node)
	if cache[node] == nil then
		cache[node] = sources[node](node, fakeRequire)
	end
	return cache[node]
end

local n_root = newNode("LumenUI")
local n_Components = newNode("Components", n_root)
local n_Core = newNode("Core", n_root)
local n_Theme = newNode("Theme", n_root)
local n_Util = newNode("Util", n_root)
local n_Components_Button = newNode("Button", n_Components)
local n_Components_Dropdown = newNode("Dropdown", n_Components)
local n_Components_Label = newNode("Label", n_Components)
local n_Components_Slider = newNode("Slider", n_Components)
local n_Components_TextBox = newNode("TextBox", n_Components)
local n_Components_Toggle = newNode("Toggle", n_Components)
local n_Core_Container = newNode("Container", n_Core)
local n_Core_Notification = newNode("Notification", n_Core)
local n_Core_Section = newNode("Section", n_Core)
local n_Core_Tab = newNode("Tab", n_Core)
local n_Core_Window = newNode("Window", n_Core)
local n_Util_Create = newNode("Create", n_Util)
local n_Util_Device = newNode("Device", n_Util)
local n_Util_Drag = newNode("Drag", n_Util)
local n_Util_Interact = newNode("Interact", n_Util)
local n_Util_Signal = newNode("Signal", n_Util)
local n_Util_Tween = newNode("Tween", n_Util)

-- Components/Button
sources[n_Components_Button] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)
local Signal = require(script.Parent.Parent.Util.Signal)
local Tween = require(script.Parent.Parent.Util.Tween)
local Device = require(script.Parent.Parent.Util.Device)
local Interact = require(script.Parent.Parent.Util.Interact)

local WHITE = Color3.new(1, 1, 1)

local Button = {}
Button.__index = Button

-- options: Name, Callback, Style = "Default" | "Primary"
function Button.new(parent, theme, options)
	local self = setmetatable({}, Button)
	self.Clicked = Signal.new()

	local primary = options.Style == "Primary"

	local idle = primary and theme.Accent or theme.Surface
	local hover = primary and theme.Accent:Lerp(WHITE, 0.14) or theme.SurfaceHover
	local press = primary and theme.Accent:Lerp(Color3.new(0, 0, 0), 0.18) or theme.Surface:Lerp(theme.Accent, 0.35)

	local scale = Create("UIScale", { Scale = 1 })

	local children = {
		Create("UICorner", { CornerRadius = theme.Corner }),
		scale,
	}

	if primary then
		-- a soft top-to-bottom shade gives the flat colour a bit of depth
		table.insert(children, Create("UIGradient", {
			Color = ColorSequence.new(WHITE, Color3.fromRGB(205, 205, 218)),
			Rotation = 90,
		}))
	else
		table.insert(children, Create("UIStroke", {
			Color = theme.Stroke,
			Transparency = 0.5,
			Thickness = 1,
			ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
		}))
	end

	local button = Create("TextButton", {
		Name = "Button",
		Size = UDim2.new(1, 0, 0, Device.rowHeight()),
		BackgroundColor3 = idle,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = options.Name or "Button",
		Font = primary and theme.FontBold or theme.Font,
		TextSize = theme.TextSize,
		TextColor3 = primary and WHITE or theme.Text,
		TextTruncate = Enum.TextTruncate.AtEnd,
		Parent = parent,
	}, children)

	self.Instance = button

	Interact.bind(button, function(state)
		local color = if state == "Press" then press elseif state == "Hover" then hover else idle
		Tween.to(button, { BackgroundColor3 = color }, 0.12)
		Tween.to(scale, { Scale = state == "Press" and 0.98 or 1 }, 0.1)
	end)

	button.Activated:Connect(function()
		self.Clicked:Fire()
		if options.Callback then
			task.spawn(options.Callback)
		end
	end)

	return self
end

function Button:SetText(text: string)
	self.Instance.Text = text
end

function Button:Destroy()
	self.Clicked:Destroy()
	self.Instance:Destroy()
end

return Button
end

-- Components/Dropdown
sources[n_Components_Dropdown] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)
local Signal = require(script.Parent.Parent.Util.Signal)
local Tween = require(script.Parent.Parent.Util.Tween)
local Device = require(script.Parent.Parent.Util.Device)
local Interact = require(script.Parent.Parent.Util.Interact)

-- Longer lists scroll instead of pushing the whole page down.
local MAX_VISIBLE = 5

local Dropdown = {}
Dropdown.__index = Dropdown

-- options: Name, Options = { ... }, Default, Callback
function Dropdown.new(parent, theme, options)
	local self = setmetatable({}, Dropdown)
	self.Changed = Signal.new()

	self._theme = theme
	self._callback = options.Callback
	self._options = options.Options or {}
	self._selected = options.Default
	self._open = false

	local rowHeight = Device.rowHeight()
	self._itemHeight = rowHeight - 6

	-- root grows when the list opens, which pushes everything below it down
	local root = Create("Frame", {
		Name = "Dropdown",
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		Parent = parent,
	}, {
		Create("UIListLayout", {
			Padding = UDim.new(0, 4),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})

	local header = Create("TextButton", {
		Name = "Header",
		LayoutOrder = 1,
		Size = UDim2.new(1, 0, 0, rowHeight),
		BackgroundColor3 = theme.Surface,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = "",
		Parent = root,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIStroke", {
			Color = theme.Stroke,
			Transparency = 0.5,
			Thickness = 1,
			ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
		}),
		Create("UIPadding", {
			PaddingLeft = UDim.new(0, 12),
			PaddingRight = UDim.new(0, 12),
		}),
		Create("TextLabel", {
			Name = "Title",
			Size = UDim2.new(0.5, -8, 1, 0),
			BackgroundTransparency = 1,
			Text = options.Name or "Dropdown",
			Font = theme.Font,
			TextSize = theme.TextSize,
			TextColor3 = theme.Text,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextTruncate = Enum.TextTruncate.AtEnd,
		}),
	})

	self._valueLabel = Create("TextLabel", {
		Name = "Value",
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.new(1, -22, 0, 0),
		Size = UDim2.new(0.5, -22, 1, 0),
		BackgroundTransparency = 1,
		Font = theme.Font,
		TextSize = theme.TextSize,
		TextColor3 = theme.Accent,
		TextXAlignment = Enum.TextXAlignment.Right,
		TextTruncate = Enum.TextTruncate.AtEnd,
		Parent = header,
	})

	-- a plain ">" rotated 90 degrees: points down when closed, up when open
	self._arrow = Create("TextLabel", {
		Name = "Arrow",
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.fromScale(1, 0.5),
		Size = UDim2.fromOffset(16, 16),
		BackgroundTransparency = 1,
		Text = ">",
		Font = theme.FontBold,
		TextSize = theme.TextSize,
		TextColor3 = theme.TextDim,
		Rotation = 90,
		Parent = header,
	})

	self._list = Create("ScrollingFrame", {
		Name = "List",
		LayoutOrder = 2,
		Size = UDim2.new(1, 0, 0, 0),
		BackgroundColor3 = theme.Surface,
		BorderSizePixel = 0,
		ScrollBarThickness = 3,
		ScrollBarImageColor3 = theme.Stroke,
		CanvasSize = UDim2.new(),
		AutomaticCanvasSize = Enum.AutomaticSize.Y,
		ScrollingDirection = Enum.ScrollingDirection.Y,
		Visible = false,
		Parent = root,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIStroke", {
			Color = theme.Stroke,
			Transparency = 0.5,
			Thickness = 1,
			ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
		}),
		Create("UIPadding", {
			PaddingTop = UDim.new(0, 4),
			PaddingBottom = UDim.new(0, 4),
			PaddingLeft = UDim.new(0, 4),
			PaddingRight = UDim.new(0, 4),
		}),
		Create("UIListLayout", {
			Padding = UDim.new(0, 2),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})

	self.Instance = root

	Interact.bind(header, function(state)
		Tween.to(header, { BackgroundColor3 = state == "Idle" and theme.Surface or theme.SurfaceHover }, 0.12)
	end)

	header.Activated:Connect(function()
		self:_setOpen(not self._open)
	end)

	self:_buildOptions()
	self:_updateLabel()
	return self
end

-- how tall the list is when fully open (capped at MAX_VISIBLE rows)
function Dropdown:_targetHeight(): number
	local count = #self._options
	if count == 0 then
		return 0
	end
	local visible = math.min(count, MAX_VISIBLE)
	return visible * (self._itemHeight + 2) + 6
end

function Dropdown:_setOpen(open: boolean)
	if open and #self._options == 0 then
		return
	end

	self._open = open
	Tween.to(self._arrow, { Rotation = open and -90 or 90 }, 0.18)

	if open then
		self._list.Visible = true
		Tween.to(self._list, { Size = UDim2.new(1, 0, 0, self:_targetHeight()) }, 0.2, Enum.EasingStyle.Quint)
	else
		local tween = Tween.to(self._list, { Size = UDim2.new(1, 0, 0, 0) }, 0.15)
		tween.Completed:Connect(function()
			if not self._open then
				self._list.Visible = false
			end
		end)
	end
end

function Dropdown:_updateLabel()
	self._valueLabel.Text = self._selected ~= nil and tostring(self._selected) or "Select..."
	self._valueLabel.TextColor3 = self._selected ~= nil and self._theme.Accent or self._theme.TextDim
end

function Dropdown:_buildOptions()
	local theme = self._theme

	-- wipe the old buttons, but keep the layout / padding / corner objects
	for _, child in self._list:GetChildren() do
		if child:IsA("TextButton") then
			child:Destroy()
		end
	end

	for index, option in self._options do
		local isSelected = option == self._selected

		local item = Create("TextButton", {
			Name = tostring(option),
			LayoutOrder = index,
			Size = UDim2.new(1, 0, 0, self._itemHeight),
			BackgroundColor3 = theme.SurfaceHover,
			BackgroundTransparency = isSelected and 0.3 or 1,
			BorderSizePixel = 0,
			AutoButtonColor = false,
			Text = tostring(option),
			Font = theme.Font,
			TextSize = theme.TextSize,
			TextColor3 = isSelected and theme.Accent or theme.Text,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextTruncate = Enum.TextTruncate.AtEnd,
			Parent = self._list,
		}, {
			Create("UICorner", { CornerRadius = UDim.new(0, 6) }),
			Create("UIPadding", { PaddingLeft = UDim.new(0, 26), PaddingRight = UDim.new(0, 8) }),
		})

		if isSelected then
			-- small accent dot marks the current choice
			Create("Frame", {
				Name = "Dot",
				AnchorPoint = Vector2.new(0, 0.5),
				Position = UDim2.new(0, -16, 0.5, 0),
				Size = UDim2.fromOffset(6, 6),
				BackgroundColor3 = theme.Accent,
				BorderSizePixel = 0,
				Parent = item,
			}, {
				Create("UICorner", { CornerRadius = UDim.new(1, 0) }),
			})
		end

		if not isSelected then
			Interact.bind(item, function(state)
				Tween.to(item, { BackgroundTransparency = state == "Idle" and 1 or 0.5 }, 0.1)
			end)
		end

		item.Activated:Connect(function()
			self:Set(option)
			self:_setOpen(false)
		end)
	end
end

function Dropdown:Set(option, silent: boolean?)
	if option == self._selected then
		return
	end

	self._selected = option
	self:_updateLabel()
	self:_buildOptions()

	if not silent then
		self.Changed:Fire(option)
		if self._callback then
			task.spawn(self._callback, option)
		end
	end
end

function Dropdown:Get()
	return self._selected
end

-- swap out the whole list, e.g. when the player list changes
function Dropdown:Refresh(newOptions: { any })
	self._options = newOptions

	if not table.find(newOptions, self._selected) then
		self._selected = nil
		self:_updateLabel()
	end

	self:_buildOptions()

	if self._open then
		if #newOptions == 0 then
			self:_setOpen(false)
		else
			Tween.to(self._list, { Size = UDim2.new(1, 0, 0, self:_targetHeight()) }, 0.15)
		end
	end
end

function Dropdown:Destroy()
	self.Changed:Destroy()
	self.Instance:Destroy()
end

return Dropdown
end

-- Components/Label
sources[n_Components_Label] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)

local Label = {}
Label.__index = Label

function Label.new(parent, theme, options)
	local self = setmetatable({}, Label)

	self.Instance = Create("TextLabel", {
		Name = "Label",
		Size = UDim2.new(1, 0, 0, 20),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		Text = options.Text or options.Name or "Label",
		Font = theme.Font,
		TextSize = theme.TextSize - 1,
		TextColor3 = theme.TextDim,
		TextWrapped = true,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextYAlignment = Enum.TextYAlignment.Top,
		Parent = parent,
	}, {
		Create("UIPadding", {
			PaddingLeft = UDim.new(0, 2),
			PaddingRight = UDim.new(0, 2),
			PaddingTop = UDim.new(0, 2),
			PaddingBottom = UDim.new(0, 2),
		}),
	})

	return self
end

function Label:SetText(text: string)
	self.Instance.Text = text
end

function Label:Destroy()
	self.Instance:Destroy()
end

return Label
end

-- Components/Slider
sources[n_Components_Slider] = function(script, require)
local UserInputService = game:GetService("UserInputService")

local Create = require(script.Parent.Parent.Util.Create)
local Signal = require(script.Parent.Parent.Util.Signal)
local Tween = require(script.Parent.Parent.Util.Tween)
local Device = require(script.Parent.Parent.Util.Device)

local Slider = {}
Slider.__index = Slider

local function isPointer(input: InputObject)
	return input.UserInputType == Enum.UserInputType.MouseButton1
		or input.UserInputType == Enum.UserInputType.Touch
end

-- 5 -> 0 decimals, 0.5 -> 1, 0.25 -> 2. Used so "60" doesn't show up as "60.0".
local function decimalsOf(step: number): number
	local decimals = 0
	while decimals < 4 do
		local scaled = step * 10 ^ decimals
		if math.abs(scaled - math.round(scaled)) < 1e-6 then
			break
		end
		decimals += 1
	end
	return decimals
end

-- options: Name, Min, Max, Default, Increment, Suffix, Callback
function Slider.new(parent, theme, options)
	local self = setmetatable({}, Slider)
	self.Changed = Signal.new()

	local touch = Device.isTouch()

	self._callback = options.Callback
	self._min = options.Min or 0
	self._max = math.max(options.Max or 100, self._min) -- Max below Min would break the maths
	self._increment = math.max(options.Increment or 1, 0)
	self._decimals = self._increment > 0 and decimalsOf(self._increment) or 2
	self._suffix = options.Suffix or ""
	self._connections = {}
	self._value = self:_snap(options.Default or self._min)

	local knobSize = touch and 20 or 16
	local knobBig = knobSize + 4

	local row = Create("Frame", {
		Name = "Slider",
		Size = UDim2.new(1, 0, 0, touch and 64 or 56),
		BackgroundColor3 = theme.Surface,
		BorderSizePixel = 0,
		Parent = parent,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIStroke", {
			Color = theme.Stroke,
			Transparency = 0.5,
			Thickness = 1,
			ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
		}),
		Create("UIPadding", {
			PaddingLeft = UDim.new(0, 12),
			PaddingRight = UDim.new(0, 12),
		}),
		Create("TextLabel", {
			Name = "Title",
			Position = UDim2.fromOffset(0, 8),
			Size = UDim2.new(0.65, 0, 0, 20),
			BackgroundTransparency = 1,
			Text = options.Name or "Slider",
			Font = theme.Font,
			TextSize = theme.TextSize,
			TextColor3 = theme.Text,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextTruncate = Enum.TextTruncate.AtEnd,
		}),
	})

	self._valueLabel = Create("TextLabel", {
		Name = "Value",
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.new(1, 0, 0, 8),
		Size = UDim2.new(0.35, 0, 0, 20),
		BackgroundTransparency = 1,
		Font = theme.FontBold,
		TextSize = theme.TextSize,
		TextColor3 = theme.Accent,
		TextXAlignment = Enum.TextXAlignment.Right,
		Parent = row,
	})

	-- The hit box is taller than the visible bar so it's easy to grab with a thumb. The side
	-- padding leaves room for the knob to overhang the ends of the track.
	local hitbox = Create("Frame", {
		Name = "Hitbox",
		AnchorPoint = Vector2.new(0, 1),
		Position = UDim2.new(0, 0, 1, -4),
		Size = UDim2.new(1, 0, 0, touch and 32 or 26),
		BackgroundTransparency = 1,
		Parent = row,
	}, {
		Create("UIPadding", {
			PaddingLeft = UDim.new(0, knobBig / 2),
			PaddingRight = UDim.new(0, knobBig / 2),
		}),
	})

	self._track = Create("Frame", {
		Name = "Track",
		AnchorPoint = Vector2.new(0, 0.5),
		Position = UDim2.fromScale(0, 0.5),
		Size = UDim2.new(1, 0, 0, touch and 8 or 6),
		BackgroundColor3 = theme.Stroke,
		BorderSizePixel = 0,
		Parent = hitbox,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(1, 0) }),
	})

	self._fill = Create("Frame", {
		Name = "Fill",
		Size = UDim2.fromScale(0, 1),
		BackgroundColor3 = Color3.new(1, 1, 1),
		BorderSizePixel = 0,
		Parent = self._track,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(1, 0) }),
		Create("UIGradient", { Color = ColorSequence.new(theme.Accent, theme.Accent2) }),
	})

	self._knob = Create("Frame", {
		Name = "Knob",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0, 0.5),
		Size = UDim2.fromOffset(knobSize, knobSize),
		BackgroundColor3 = Color3.new(1, 1, 1),
		BorderSizePixel = 0,
		ZIndex = 2,
		Parent = self._track,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(1, 0) }),
		Create("UIStroke", { Color = theme.Accent, Thickness = 2 }),
	})

	self.Instance = row

	local dragging = false
	local lockedScroller: ScrollingFrame? = nil

	-- Touching a slider inside a ScrollingFrame would scroll the page as well, so the page
	-- is frozen for as long as the finger is on the slider.
	local function setDragging(active: boolean)
		dragging = active
		Tween.to(self._knob, {
			Size = UDim2.fromOffset(active and knobBig or knobSize, active and knobBig or knobSize),
		}, 0.1)

		if active then
			lockedScroller = row:FindFirstAncestorWhichIsA("ScrollingFrame")
			if lockedScroller then
				lockedScroller.ScrollingEnabled = false
			end
		elseif lockedScroller then
			lockedScroller.ScrollingEnabled = true
			lockedScroller = nil
		end
	end

	local function updateFromX(x: number)
		local width = self._track.AbsoluteSize.X
		if width <= 0 then
			return
		end
		local alpha = math.clamp((x - self._track.AbsolutePosition.X) / width, 0, 1)
		self:Set(self._min + (self._max - self._min) * alpha)
	end

	hitbox.InputBegan:Connect(function(input)
		if isPointer(input) then
			setDragging(true)
			updateFromX(input.Position.X)
		end
	end)

	table.insert(self._connections, UserInputService.InputChanged:Connect(function(input)
		if not dragging then
			return
		end
		if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
			updateFromX(input.Position.X)
		end
	end))

	table.insert(self._connections, UserInputService.InputEnded:Connect(function(input)
		if dragging and isPointer(input) then
			setDragging(false)
		end
	end))

	-- These connections live on UserInputService, so destroying the window would NOT clean
	-- them up by itself. Hook the row's own destruction instead.
	row.Destroying:Connect(function()
		if dragging then
			setDragging(false)
		end
		self:_disconnect()
	end)

	self:_render(false)
	return self
end

function Slider:_disconnect()
	for _, connection in self._connections do
		connection:Disconnect()
	end
	table.clear(self._connections)
end

-- Snap to the increment, then clamp. The round() cleans up float noise like 0.30000000004.
function Slider:_snap(value: number): number
	if self._increment > 0 then
		value = math.floor((value - self._min) / self._increment + 0.5) * self._increment + self._min
	end
	return math.clamp(math.round(value * 10000) / 10000, self._min, self._max)
end

function Slider:_render(animate: boolean)
	local range = self._max - self._min
	local alpha = range > 0 and (self._value - self._min) / range or 0

	if animate then
		Tween.to(self._fill, { Size = UDim2.fromScale(alpha, 1) }, 0.06)
		Tween.to(self._knob, { Position = UDim2.fromScale(alpha, 0.5) }, 0.06)
	else
		self._fill.Size = UDim2.fromScale(alpha, 1)
		self._knob.Position = UDim2.fromScale(alpha, 0.5)
	end

	self._valueLabel.Text = string.format("%." .. self._decimals .. "f", self._value) .. self._suffix
end

function Slider:Set(value: number, silent: boolean?)
	value = self:_snap(value)

	if value == self._value then
		return
	end

	self._value = value
	self:_render(true)

	if not silent then
		self.Changed:Fire(value)
		if self._callback then
			task.spawn(self._callback, value)
		end
	end
end

function Slider:Get(): number
	return self._value
end

function Slider:Destroy()
	self:_disconnect()
	self.Changed:Destroy()
	self.Instance:Destroy()
end

return Slider
end

-- Components/TextBox
sources[n_Components_TextBox] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)
local Signal = require(script.Parent.Parent.Util.Signal)
local Tween = require(script.Parent.Parent.Util.Tween)
local Device = require(script.Parent.Parent.Util.Device)

local TextBox = {}
TextBox.__index = TextBox

-- options: Name, Default, Placeholder, ClearOnFocus, Callback(text, enterPressed)
function TextBox.new(parent, theme, options)
	local self = setmetatable({}, TextBox)
	self.Changed = Signal.new()
	self._callback = options.Callback

	local height = Device.rowHeight()

	local row = Create("Frame", {
		Name = "TextBox",
		Size = UDim2.new(1, 0, 0, height),
		BackgroundColor3 = theme.Surface,
		BorderSizePixel = 0,
		Parent = parent,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIStroke", {
			Color = theme.Stroke,
			Transparency = 0.5,
			Thickness = 1,
			ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
		}),
		Create("UIPadding", {
			PaddingLeft = UDim.new(0, 12),
			PaddingRight = UDim.new(0, 6),
		}),
		Create("TextLabel", {
			Name = "Title",
			Size = UDim2.new(0.42, 0, 1, 0),
			BackgroundTransparency = 1,
			Text = options.Name or "TextBox",
			Font = theme.Font,
			TextSize = theme.TextSize,
			TextColor3 = theme.Text,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextTruncate = Enum.TextTruncate.AtEnd,
		}),
	})

	local stroke = Create("UIStroke", {
		Color = theme.Stroke,
		Thickness = 1,
		ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	})

	self._box = Create("TextBox", {
		Name = "Input",
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.fromScale(1, 0.5),
		Size = UDim2.new(0.56, 0, 0, height - 12),
		BackgroundColor3 = theme.Background,
		BorderSizePixel = 0,
		Text = options.Default or "",
		PlaceholderText = options.Placeholder or "Type here...",
		PlaceholderColor3 = theme.TextDim,
		ClearTextOnFocus = options.ClearOnFocus == true,
		Font = theme.Font,
		TextSize = theme.TextSize - 1,
		TextColor3 = theme.Text,
		TextXAlignment = Enum.TextXAlignment.Left,
		-- Not TextTruncate: while the text is being edited the box has to scroll with the cursor.
		ClipsDescendants = true,
		Parent = row,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(0, 6) }),
		Create("UIPadding", {
			PaddingLeft = UDim.new(0, 8),
			PaddingRight = UDim.new(0, 8),
		}),
		stroke,
	})

	self.Instance = row

	self._box.Focused:Connect(function()
		Tween.to(stroke, { Color = theme.Accent }, 0.12)
	end)

	self._box.FocusLost:Connect(function(enterPressed)
		Tween.to(stroke, { Color = theme.Stroke }, 0.12)

		local text = self._box.Text
		self.Changed:Fire(text, enterPressed)
		if self._callback then
			task.spawn(self._callback, text, enterPressed)
		end
	end)

	return self
end

function TextBox:Set(text: string)
	self._box.Text = text
end

function TextBox:Get(): string
	return self._box.Text
end

function TextBox:Destroy()
	self.Changed:Destroy()
	self.Instance:Destroy()
end

return TextBox
end

-- Components/Toggle
sources[n_Components_Toggle] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)
local Signal = require(script.Parent.Parent.Util.Signal)
local Tween = require(script.Parent.Parent.Util.Tween)
local Device = require(script.Parent.Parent.Util.Device)
local Interact = require(script.Parent.Parent.Util.Interact)

local TRACK_WIDTH = 44
local TRACK_HEIGHT = 24
local KNOB_SIZE = 18
local KNOB_STRETCH = 22 -- the knob gets a little wider while it is pressed
local KNOB_GAP = 3

local Toggle = {}
Toggle.__index = Toggle

-- options: Name, Description (optional second line), Default, Callback
function Toggle.new(parent, theme, options)
	local self = setmetatable({}, Toggle)
	self.Changed = Signal.new()

	self._theme = theme
	self._callback = options.Callback
	self._value = options.Default == true
	self._pressed = false

	local hasDescription = options.Description ~= nil
	local height = Device.rowHeight() + (hasDescription and 12 or 0)

	local children = {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIStroke", {
			Color = theme.Stroke,
			Transparency = 0.5,
			Thickness = 1,
			ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
		}),
		Create("UIPadding", {
			PaddingLeft = UDim.new(0, 12),
			PaddingRight = UDim.new(0, 12),
		}),
		Create("TextLabel", {
			Name = "Title",
			Position = hasDescription and UDim2.fromOffset(0, 7) or UDim2.new(),
			Size = hasDescription and UDim2.new(1, -(TRACK_WIDTH + 12), 0, 20) or UDim2.new(1, -(TRACK_WIDTH + 12), 1, 0),
			BackgroundTransparency = 1,
			Text = options.Name or "Toggle",
			Font = theme.Font,
			TextSize = theme.TextSize,
			TextColor3 = theme.Text,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextTruncate = Enum.TextTruncate.AtEnd,
		}),
	}

	if hasDescription then
		table.insert(children, Create("TextLabel", {
			Name = "Description",
			Position = UDim2.fromOffset(0, 27),
			Size = UDim2.new(1, -(TRACK_WIDTH + 12), 0, 14),
			BackgroundTransparency = 1,
			Text = options.Description,
			Font = theme.Font,
			TextSize = theme.TextSize - 2,
			TextColor3 = theme.TextDim,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextTruncate = Enum.TextTruncate.AtEnd,
		}))
	end

	local row = Create("TextButton", {
		Name = "Toggle",
		Size = UDim2.new(1, 0, 0, height),
		BackgroundColor3 = theme.Surface,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = "",
		Parent = parent,
	}, children)

	self._track = Create("Frame", {
		Name = "Track",
		Size = UDim2.fromOffset(TRACK_WIDTH, TRACK_HEIGHT),
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.fromScale(1, 0.5),
		BackgroundColor3 = theme.Stroke,
		BorderSizePixel = 0,
		Parent = row,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(1, 0) }),
	})

	self._knob = Create("Frame", {
		Name = "Knob",
		Size = UDim2.fromOffset(KNOB_SIZE, KNOB_SIZE),
		AnchorPoint = Vector2.new(0, 0.5),
		Position = UDim2.new(0, KNOB_GAP, 0.5, 0),
		BackgroundColor3 = theme.TextDim,
		BorderSizePixel = 0,
		Parent = self._track,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(1, 0) }),
	})

	self.Instance = row

	Interact.bind(row, function(state)
		self._pressed = state == "Press"
		Tween.to(row, { BackgroundColor3 = state == "Idle" and theme.Surface or theme.SurfaceHover }, 0.12)
		self:_render(true)
	end)

	row.Activated:Connect(function()
		self:Set(not self._value)
	end)

	self:_render(false)
	return self
end

function Toggle:_render(animate: boolean)
	local theme = self._theme
	local on = self._value

	local knobWidth = self._pressed and KNOB_STRETCH or KNOB_SIZE
	local knobX = on and (TRACK_WIDTH - knobWidth - KNOB_GAP) or KNOB_GAP

	local trackGoal = { BackgroundColor3 = on and theme.Accent or theme.Stroke }
	local knobGoal = {
		Size = UDim2.fromOffset(knobWidth, KNOB_SIZE),
		Position = UDim2.new(0, knobX, 0.5, 0),
		BackgroundColor3 = on and Color3.new(1, 1, 1) or theme.TextDim,
	}

	if animate then
		Tween.to(self._track, trackGoal, 0.18)
		Tween.to(self._knob, knobGoal, 0.18)
	else
		self._track.BackgroundColor3 = trackGoal.BackgroundColor3
		self._knob.Size = knobGoal.Size
		self._knob.Position = knobGoal.Position
		self._knob.BackgroundColor3 = knobGoal.BackgroundColor3
	end
end

-- silent = true skips the callback / Changed signal (handy when loading configs)
function Toggle:Set(value: boolean, silent: boolean?)
	value = not not value
	if value == self._value then
		return
	end

	self._value = value
	self:_render(true)

	if not silent then
		self.Changed:Fire(value)
		if self._callback then
			task.spawn(self._callback, value)
		end
	end
end

function Toggle:Get(): boolean
	return self._value
end

function Toggle:Destroy()
	self.Changed:Destroy()
	self.Instance:Destroy()
end

return Toggle
end

-- Components
sources[n_Components] = function(script, require)
-- One place that lists every component. Container.luau loops over this table and
-- generates the AddButton / AddToggle / ... methods automatically, so adding a new
-- component is just: write the file, add one line here.

return {
	Label = require(script.Label),
	Button = require(script.Button),
	Toggle = require(script.Toggle),
	Slider = require(script.Slider),
	TextBox = require(script.TextBox),
	Dropdown = require(script.Dropdown),
}
end

-- Core/Container
sources[n_Core_Container] = function(script, require)
-- Both Tabs and Sections can hold components. Instead of copy/pasting the same
-- AddButton/AddToggle/... methods into each one, we bolt them on with this mixin.
--
-- The class needs to have two fields:
--   self._content  -> the Instance that components get parented to
--   self._theme    -> the theme table

local Components = require(script.Parent.Parent.Components)

local Container = {}

function Container.mixin(class)
	for name, constructor in Components do
		class["Add" .. name] = function(self, options)
			return constructor.new(self._content, self._theme, options or {})
		end
	end
end

return Container
end

-- Core/Notification
sources[n_Core_Notification] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)
local Tween = require(script.Parent.Parent.Util.Tween)

local Notification = {}
Notification.__index = Notification

-- which theme colour each notification type uses
local TYPE_COLORS = {
	Info = "Accent",
	Success = "Success",
	Warning = "Warning",
	Error = "Error",
}

function Notification.new(gui: ScreenGui, theme)
	local self = setmetatable({}, Notification)
	self._theme = theme
	self._compact = false

	self._holder = Create("Frame", {
		Name = "Notifications",
		BackgroundTransparency = 1,
		ZIndex = 50,
		Parent = gui,
	})

	self._list = Create("UIListLayout", {
		Padding = UDim.new(0, 8),
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = self._holder,
	})

	self:SetLayout(false, gui.AbsoluteSize)
	return self
end

-- Desktop: stacked in the bottom-right corner.
-- Phones / narrow windows: full-width cards dropping in from the top, away from the thumbs.
function Notification:SetLayout(compact: boolean, viewport: Vector2)
	self._compact = compact

	local width = math.clamp(viewport.X - 24, 200, 330)
	local holder = self._holder
	local list = self._list

	if compact then
		holder.AnchorPoint = Vector2.new(0.5, 0)
		holder.Position = UDim2.new(0.5, 0, 0, 12)
		holder.Size = UDim2.new(0, width, 1, -24)
		list.VerticalAlignment = Enum.VerticalAlignment.Top
		list.HorizontalAlignment = Enum.HorizontalAlignment.Center
	else
		holder.AnchorPoint = Vector2.new(1, 1)
		holder.Position = UDim2.new(1, -16, 1, -16)
		holder.Size = UDim2.new(0, width, 1, -32)
		list.VerticalAlignment = Enum.VerticalAlignment.Bottom
		list.HorizontalAlignment = Enum.HorizontalAlignment.Right
	end
end

-- options: Title, Content, Duration (seconds, 0 = stays until tapped), Type = "Info" | "Success" | "Warning" | "Error"
function Notification:Push(options)
	local theme = self._theme
	local duration = options.Duration or 4
	local timed = duration > 0 and duration < math.huge
	local accent = theme[TYPE_COLORS[options.Type or "Info"] or "Accent"] or theme.Accent

	local slideOffset = self._compact and UDim2.fromOffset(0, -24) or UDim2.fromOffset(32, 0)

	-- The list layout owns the slot's position, so the card slides around inside the slot.
	local slot = Create("Frame", {
		Name = "NotificationSlot",
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		Parent = self._holder,
	})

	-- CanvasGroup lets us fade the whole card (text, stroke and all) with one property
	local card = Create("CanvasGroup", {
		Name = "Notification",
		Position = slideOffset,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundColor3 = theme.Surface,
		BorderSizePixel = 0,
		GroupTransparency = 1,
		Active = true, -- so a tap on the card doesn't also hit the game behind it
		Parent = slot,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIStroke", { Color = theme.Stroke, Thickness = 1 }),
		Create("Frame", {
			Name = "Bar",
			Size = UDim2.new(0, 3, 1, 0),
			BackgroundColor3 = accent,
			BorderSizePixel = 0,
		}),
		Create("Frame", {
			Name = "Content",
			Size = UDim2.new(1, 0, 0, 0),
			AutomaticSize = Enum.AutomaticSize.Y,
			BackgroundTransparency = 1,
		}, {
			Create("UIPadding", {
				PaddingTop = UDim.new(0, 10),
				PaddingBottom = UDim.new(0, 12),
				PaddingLeft = UDim.new(0, 16),
				PaddingRight = UDim.new(0, 12),
			}),
			Create("UIListLayout", {
				Padding = UDim.new(0, 2),
				SortOrder = Enum.SortOrder.LayoutOrder,
			}),
			Create("TextLabel", {
				Name = "Title",
				LayoutOrder = 1,
				Size = UDim2.new(1, 0, 0, 18),
				BackgroundTransparency = 1,
				Text = options.Title or "Notice",
				Font = theme.FontBold,
				TextSize = theme.TextSize,
				TextColor3 = theme.Text,
				TextXAlignment = Enum.TextXAlignment.Left,
				TextTruncate = Enum.TextTruncate.AtEnd,
			}),
			Create("TextLabel", {
				Name = "Body",
				LayoutOrder = 2,
				Size = UDim2.new(1, 0, 0, 0),
				AutomaticSize = Enum.AutomaticSize.Y,
				BackgroundTransparency = 1,
				Text = options.Content or "",
				Font = theme.Font,
				TextSize = theme.TextSize - 1,
				TextColor3 = theme.TextDim,
				TextWrapped = true,
				TextXAlignment = Enum.TextXAlignment.Left,
				TextYAlignment = Enum.TextYAlignment.Top,
			}),
		}),
	})

	local progress
	if timed then
		-- thin bar along the bottom edge that runs out when the card is about to leave
		progress = Create("Frame", {
			Name = "Progress",
			AnchorPoint = Vector2.new(0, 1),
			Position = UDim2.fromScale(0, 1),
			Size = UDim2.new(1, 0, 0, 2),
			BackgroundColor3 = accent,
			BackgroundTransparency = 0.25,
			BorderSizePixel = 0,
			Parent = card,
		})
	end

	Tween.to(card, { GroupTransparency = 0, Position = UDim2.new() }, 0.3, Enum.EasingStyle.Quint)
	if progress then
		Tween.to(progress, { Size = UDim2.new(0, 0, 0, 2) }, duration, Enum.EasingStyle.Linear)
	end

	local closing = false
	local function dismiss()
		if closing or not card.Parent then
			return -- already leaving, or the window was destroyed in the meantime
		end
		closing = true

		local tween = Tween.to(card, { GroupTransparency = 1, Position = slideOffset }, 0.25)
		tween.Completed:Connect(function()
			slot:Destroy()
		end)
	end

	-- tap / click a card to get rid of it early
	card.InputBegan:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
			dismiss()
		end
	end)

	if timed then
		task.delay(duration, dismiss)
	end
end

return Notification
end

-- Core/Section
sources[n_Core_Section] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)
local Tween = require(script.Parent.Parent.Util.Tween)
local Device = require(script.Parent.Parent.Util.Device)
local Interact = require(script.Parent.Parent.Util.Interact)
local Container = require(script.Parent.Container)

local Section = {}
Section.__index = Section

-- options (all optional): Collapsible = true, Collapsed = true
function Section.new(parent, theme, title: string, options)
	options = options or {}

	local self = setmetatable({}, Section)
	self._theme = theme
	self._collapsible = options.Collapsible == true or options.Collapsed ~= nil
	self._collapsed = options.Collapsed == true

	self.Instance = Create("Frame", {
		Name = "Section",
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		Parent = parent,
	}, {
		Create("UIListLayout", {
			Padding = UDim.new(0, 6),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})

	local header = Create("TextButton", {
		Name = "Header",
		LayoutOrder = 1,
		Size = UDim2.new(1, 0, 0, Device.isTouch() and 28 or 22),
		BackgroundTransparency = 1,
		AutoButtonColor = false,
		Active = self._collapsible,
		Text = "",
		Parent = self.Instance,
	}, {
		Create("UIPadding", { PaddingLeft = UDim.new(0, 2), PaddingRight = UDim.new(0, 4) }),
		-- little gradient bar in front of the title
		Create("Frame", {
			Name = "Marker",
			AnchorPoint = Vector2.new(0, 0.5),
			Position = UDim2.fromScale(0, 0.5),
			Size = UDim2.fromOffset(3, 12),
			BackgroundColor3 = Color3.new(1, 1, 1),
			BorderSizePixel = 0,
		}, {
			Create("UICorner", { CornerRadius = UDim.new(1, 0) }),
			Create("UIGradient", { Color = ColorSequence.new(theme.Accent, theme.Accent2), Rotation = 90 }),
		}),
		Create("TextLabel", {
			Name = "Title",
			Position = UDim2.fromOffset(11, 0),
			Size = UDim2.new(1, -30, 1, 0),
			BackgroundTransparency = 1,
			Text = string.upper(title or "Section"),
			Font = theme.FontBold,
			TextSize = theme.TextSize - 3,
			TextColor3 = theme.TextDim,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextTruncate = Enum.TextTruncate.AtEnd,
		}),
	})

	if self._collapsible then
		self._arrow = Create("TextLabel", {
			Name = "Arrow",
			AnchorPoint = Vector2.new(1, 0.5),
			Position = UDim2.fromScale(1, 0.5),
			Size = UDim2.fromOffset(16, 16),
			BackgroundTransparency = 1,
			Text = ">",
			Font = theme.FontBold,
			TextSize = theme.TextSize - 2,
			TextColor3 = theme.TextDim,
			Rotation = self._collapsed and 0 or 90,
			Parent = header,
		})

		Interact.bind(header, function(state)
			Tween.to(header:FindFirstChild("Title"), { TextColor3 = state == "Idle" and theme.TextDim or theme.Text }, 0.12)
		end)

		header.Activated:Connect(function()
			self:SetCollapsed(not self._collapsed)
		end)
	end

	self._content = Create("Frame", {
		Name = "Content",
		LayoutOrder = 2,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundColor3 = theme.Section,
		BorderSizePixel = 0,
		Visible = not self._collapsed,
		Parent = self.Instance,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		Create("UIStroke", {
			Color = theme.Stroke,
			Transparency = 0.35,
			Thickness = 1,
			ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
		}),
		Create("UIPadding", {
			PaddingTop = UDim.new(0, 8),
			PaddingBottom = UDim.new(0, 8),
			PaddingLeft = UDim.new(0, 8),
			PaddingRight = UDim.new(0, 8),
		}),
		Create("UIListLayout", {
			Padding = UDim.new(0, 6),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})

	return self
end

function Section:SetCollapsed(collapsed: boolean)
	if not self._collapsible then
		return
	end

	self._collapsed = collapsed
	self._content.Visible = not collapsed
	Tween.to(self._arrow, { Rotation = collapsed and 0 or 90 }, 0.15)
end

function Section:Destroy()
	self.Instance:Destroy()
end

Container.mixin(Section)

return Section
end

-- Core/Tab
sources[n_Core_Tab] = function(script, require)
local Create = require(script.Parent.Parent.Util.Create)
local Tween = require(script.Parent.Parent.Util.Tween)
local Device = require(script.Parent.Parent.Util.Device)
local Interact = require(script.Parent.Parent.Util.Interact)
local Container = require(script.Parent.Container)
local Section = require(script.Parent.Section)

local Tab = {}
Tab.__index = Tab

function Tab.new(window, name: string)
	local self = setmetatable({}, Tab)
	local theme = window.Theme

	self.Name = name
	self._window = window
	self._theme = theme
	self._active = false
	self._state = "Idle"
	self._compact = false

	self._indicator = Create("Frame", {
		Name = "Indicator",
		BackgroundColor3 = Color3.new(1, 1, 1),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(1, 0) }),
		Create("UIGradient", { Color = ColorSequence.new(theme.Accent, theme.Accent2), Rotation = 90 }),
	})

	self._buttonPadding = Create("UIPadding", {
		PaddingLeft = UDim.new(0, 14),
		PaddingRight = UDim.new(0, 14),
	})

	self._button = Create("TextButton", {
		Name = name,
		Size = UDim2.new(1, 0, 0, Device.isTouch() and 40 or 34),
		BackgroundColor3 = theme.Surface,
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = name,
		Font = theme.Font,
		TextSize = theme.TextSize,
		TextColor3 = theme.TextDim,
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = window.TabList,
	}, {
		Create("UICorner", { CornerRadius = theme.Corner }),
		self._buttonPadding,
		self._indicator,
	})

	self._pagePadding = Create("UIPadding", {
		PaddingTop = UDim.new(0, 12),
		PaddingBottom = UDim.new(0, 12),
		PaddingLeft = UDim.new(0, 12),
		PaddingRight = UDim.new(0, 14),
	})

	-- _content is where the Container mixin drops new components
	self._content = Create("ScrollingFrame", {
		Name = name,
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		ScrollBarThickness = Device.isTouch() and 4 or 3,
		ScrollBarImageColor3 = theme.Stroke,
		CanvasSize = UDim2.new(),
		AutomaticCanvasSize = Enum.AutomaticSize.Y,
		ScrollingDirection = Enum.ScrollingDirection.Y,
		Visible = false,
		Parent = window.Pages,
	}, {
		self._pagePadding,
		Create("UIListLayout", {
			Padding = UDim.new(0, 12),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})

	Interact.bind(self._button, function(state)
		self._state = state
		self:_refresh()
	end)

	self._button.Activated:Connect(function()
		self:Select()
	end)

	self:_setCompact(window._compact == true)
	self:_refresh()

	return self
end

function Tab:Select()
	self._window:_selectTab(self)
end

-- Sidebar button (desktop) or button in the top strip (narrow screens, phones in portrait).
-- Called by the window whenever its layout changes.
function Tab:_setCompact(compact: boolean)
	self._compact = compact

	if compact then
		self._button.Size = UDim2.fromOffset(0, Device.isTouch() and 34 or 30)
		self._button.AutomaticSize = Enum.AutomaticSize.X
		self._button.TextXAlignment = Enum.TextXAlignment.Center
		self._indicator.AnchorPoint = Vector2.new(0.5, 1)
		self._indicator.Position = UDim2.new(0.5, 0, 1, 0)
		self._indicator.Size = UDim2.new(0.5, 0, 0, 3)
		self._pagePadding.PaddingLeft = UDim.new(0, 10)
		self._pagePadding.PaddingRight = UDim.new(0, 12)
		self._pagePadding.PaddingTop = UDim.new(0, 10)
	else
		self._button.Size = UDim2.new(1, 0, 0, Device.isTouch() and 40 or 34)
		self._button.AutomaticSize = Enum.AutomaticSize.None
		self._button.TextXAlignment = Enum.TextXAlignment.Left
		-- the button has 14px of left padding, which shifts its children, so pull the bar back out
		self._indicator.AnchorPoint = Vector2.new(0, 0.5)
		self._indicator.Position = UDim2.new(0, -14, 0.5, 0)
		self._indicator.Size = UDim2.fromOffset(3, 16)
		self._pagePadding.PaddingLeft = UDim.new(0, 12)
		self._pagePadding.PaddingRight = UDim.new(0, 14)
		self._pagePadding.PaddingTop = UDim.new(0, 12)
	end
end

function Tab:_refresh()
	local theme = self._theme
	local state = self._state

	local color, transparency, text
	if self._active then
		color = theme.Accent
		transparency = state == "Press" and 0.72 or 0.86
		text = theme.Text
	else
		color = theme.Surface
		transparency = if state == "Press" then 0.3 elseif state == "Hover" then 0.6 else 1
		text = state == "Idle" and theme.TextDim or theme.Text
	end

	Tween.to(self._button, {
		BackgroundColor3 = color,
		BackgroundTransparency = transparency,
		TextColor3 = text,
	}, 0.15)
	Tween.to(self._indicator, { BackgroundTransparency = self._active and 0 or 1 }, 0.15)
end

-- called by the window, not meant to be used directly
function Tab:_setActive(active: boolean)
	self._active = active
	self._content.Visible = active
	self:_refresh()

	if active then
		-- the page slides up a few pixels as it appears
		self._content.Position = UDim2.fromOffset(0, 10)
		Tween.to(self._content, { Position = UDim2.new() }, 0.25, Enum.EasingStyle.Quint)
	end
end

-- options (optional): { Collapsible = true, Collapsed = false }
function Tab:AddSection(title: string, options)
	return Section.new(self._content, self._theme, title, options)
end

function Tab:Destroy()
	self._button:Destroy()
	self._content:Destroy()
end

Container.mixin(Tab)

return Tab
end

-- Core/Window
sources[n_Core_Window] = function(script, require)
local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")

local Create = require(script.Parent.Parent.Util.Create)
local Tween = require(script.Parent.Parent.Util.Tween)
local Signal = require(script.Parent.Parent.Util.Signal)
local Drag = require(script.Parent.Parent.Util.Drag)
local Device = require(script.Parent.Parent.Util.Device)
local Interact = require(script.Parent.Parent.Util.Interact)
local Theme = require(script.Parent.Parent.Theme)
local Tab = require(script.Parent.Tab)
local Notification = require(script.Parent.Notification)

local Window = {}
Window.__index = Window

local WHITE = Color3.new(1, 1, 1)

local SIDEBAR_WIDTH = 150
local TAB_STRIP_HEIGHT = 44 -- the horizontal tab bar used on narrow screens
local COMPACT_WIDTH = 520 -- windows narrower than this switch to the tab strip
local SCREEN_MARGIN = 10 -- minimum gap between the window and the screen edge
local HIDDEN_SCALE = 0.94 -- the window grows from / shrinks to this size when toggled

-- In Studio / normal games this is just PlayerGui. If the environment offers gethui()
-- (most executors do) we use that instead, since PlayerGui can get wiped on respawn
-- or inspected by the game.
local function getDefaultParent()
	local ok, hidden = pcall(function()
		return gethui and gethui()
	end)
	if ok and hidden then
		return hidden
	end
	return Players.LocalPlayer:WaitForChild("PlayerGui")
end

-- Running a script twice would otherwise leave two windows stacked on top of each other.
local function removeExisting(parent: Instance, key: string)
	for _, child in parent:GetChildren() do
		if child:IsA("ScreenGui") and child:GetAttribute("LumenKey") == key then
			child:Destroy()
		end
	end
end

-- Round-ish button for the title bar. `bars` are the rotations of the line(s) that draw the
-- icon: { 0 } is a dash (minimise), { 45, -45 } is a cross (close).
local function makeIconButton(parent: Instance, theme, name: string, rightOffset: number, hoverColor: Color3, bars: { number })
	local size = Device.isTouch() and 36 or 28

	local button = Create("TextButton", {
		Name = name,
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.new(1, rightOffset, 0.5, 0),
		Size = UDim2.fromOffset(size, size),
		BackgroundColor3 = hoverColor,
		BackgroundTransparency = 1,
		AutoButtonColor = false,
		Text = "",
		Parent = parent,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(0, 8) }),
	})

	local lines = {}
	for _, rotation in bars do
		table.insert(lines, Create("Frame", {
			AnchorPoint = Vector2.new(0.5, 0.5),
			Position = UDim2.fromScale(0.5, 0.5),
			Size = UDim2.fromOffset(12, 2),
			Rotation = rotation,
			BackgroundColor3 = theme.TextDim,
			BorderSizePixel = 0,
			Parent = button,
		}, {
			Create("UICorner", { CornerRadius = UDim.new(1, 0) }),
		}))
	end

	Interact.bind(button, function(state)
		local transparency = if state == "Press" then 0.6 elseif state == "Hover" then 0.8 else 1
		local color = state == "Idle" and theme.TextDim or hoverColor

		Tween.to(button, { BackgroundTransparency = transparency }, 0.12)
		for _, line in lines do
			Tween.to(line, { BackgroundColor3 = color }, 0.12)
		end
	end)

	return button
end

-- options:
--   Title, Subtitle        text in the title bar
--   Size                   UDim2 (offset = wanted size). Shrinks automatically to fit small screens.
--   ToggleKey              Enum.KeyCode that shows/hides the window (false = no key)
--   Launcher               true/false: draggable round button that shows/hides the window.
--                          Default: on for phones and tablets, off elsewhere.
--   Preset                 "Dark" (default) | "Light"
--   Theme                  table of colour overrides, see Theme.luau
--   Id                     windows with the same Id (default: the Title) replace each other
--   Parent                 where the ScreenGui goes
function Window.new(options)
	options = options or {}

	local self = setmetatable({}, Window)
	self.Theme = Theme.extend(Theme.Presets[options.Preset] or Theme.Dark, options.Theme)
	self.Tabs = {}
	self.Destroyed = Signal.new()

	self._connections = {}
	self._activeTab = nil
	self._visible = true
	self._compact = false
	self._destroyed = false
	self._size = Vector2.new(580, 400)
	self._sizeOption = options.Size or UDim2.fromOffset(580, 400)
	self._topbarHeight = Device.isTouch() and 48 or 44

	self._toggleKey = options.ToggleKey
	if self._toggleKey == nil then
		self._toggleKey = Enum.KeyCode.RightShift
	end

	local theme = self.Theme
	local parent = options.Parent or getDefaultParent()
	local key = options.Id or options.Title or "LumenUI"

	removeExisting(parent, key)

	self.Gui = Create("ScreenGui", {
		Name = "LumenUI",
		ResetOnSpawn = false,
		ZIndexBehavior = Enum.ZIndexBehavior.Sibling,
		DisplayOrder = 100,
		Parent = parent,
	})
	self.Gui:SetAttribute("LumenKey", key)

	Interact.retain()

	-- If something else destroys the ScreenGui (the next run of the script, say), still clean up
	-- the connections we made on UserInputService.
	self.Gui.Destroying:Connect(function()
		self:Destroy(true)
	end)

	---- window frame --------------------------------------------------------------------

	-- Main is the thing that moves and scales. The shadows and the body are children of it.
	self._scale = Create("UIScale", { Scale = HIDDEN_SCALE })

	self.Main = Create("Frame", {
		Name = "Main",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.5),
		Size = UDim2.fromOffset(580, 400),
		BackgroundTransparency = 1,
		Parent = self.Gui,
	}, {
		self._scale,
		-- two translucent layers fake a soft drop shadow without any image assets
		Create("Frame", {
			Name = "ShadowFar",
			AnchorPoint = Vector2.new(0.5, 0.5),
			Position = UDim2.new(0.5, 0, 0.5, 10),
			Size = UDim2.new(1, 44, 1, 44),
			BackgroundColor3 = Color3.new(0, 0, 0),
			BackgroundTransparency = 0.94,
			BorderSizePixel = 0,
			ZIndex = 0,
		}, { Create("UICorner", { CornerRadius = UDim.new(0, 32) }) }),
		Create("Frame", {
			Name = "ShadowNear",
			AnchorPoint = Vector2.new(0.5, 0.5),
			Position = UDim2.new(0.5, 0, 0.5, 5),
			Size = UDim2.new(1, 20, 1, 20),
			BackgroundColor3 = Color3.new(0, 0, 0),
			BackgroundTransparency = 0.86,
			BorderSizePixel = 0,
			ZIndex = 0,
		}, { Create("UICorner", { CornerRadius = UDim.new(0, 24) }) }),
	})

	self.Body = Create("Frame", {
		Name = "Body",
		Size = UDim2.fromScale(1, 1),
		BackgroundColor3 = theme.Background,
		BorderSizePixel = 0,
		ClipsDescendants = true,
		ZIndex = 1,
		Parent = self.Main,
	}, {
		Create("UICorner", { CornerRadius = theme.WindowCorner }),
		Create("UIStroke", { Color = theme.Stroke, Thickness = 1, ApplyStrokeMode = Enum.ApplyStrokeMode.Border }),
		-- very light top-to-bottom shade
		Create("UIGradient", { Color = ColorSequence.new(WHITE, Color3.fromRGB(230, 230, 238)), Rotation = 90 }),
	})

	---- title bar (also the drag handle) -----------------------------------------------

	local topHeight = self._topbarHeight
	local hasSubtitle = options.Subtitle ~= nil

	local topBar = Create("Frame", {
		Name = "TopBar",
		Size = UDim2.new(1, 0, 0, topHeight),
		BackgroundTransparency = 1,
		Parent = self.Body,
	}, {
		-- logo: gradient tile with a white diamond
		Create("Frame", {
			Name = "Logo",
			AnchorPoint = Vector2.new(0, 0.5),
			Position = UDim2.new(0, 14, 0.5, 0),
			Size = UDim2.fromOffset(24, 24),
			BackgroundColor3 = WHITE,
			BorderSizePixel = 0,
		}, {
			Create("UICorner", { CornerRadius = UDim.new(0, 8) }),
			Create("UIGradient", { Color = ColorSequence.new(theme.Accent, theme.Accent2), Rotation = 45 }),
			Create("Frame", {
				AnchorPoint = Vector2.new(0.5, 0.5),
				Position = UDim2.fromScale(0.5, 0.5),
				Size = UDim2.fromOffset(9, 9),
				Rotation = 45,
				BackgroundColor3 = WHITE,
				BorderSizePixel = 0,
			}, { Create("UICorner", { CornerRadius = UDim.new(0, 2) }) }),
		}),
	})

	-- room the title must leave free on the right for the two buttons
	local buttonSize = Device.isTouch() and 36 or 28
	local titleReserve = 48 + 22 + buttonSize * 2

	self._titleLabel = Create("TextLabel", {
		Name = "Title",
		Position = UDim2.fromOffset(48, hasSubtitle and 6 or 0),
		Size = UDim2.new(1, -titleReserve, hasSubtitle and 0 or 1, hasSubtitle and 18 or 0),
		BackgroundTransparency = 1,
		Text = options.Title or "Lumen UI",
		Font = theme.FontBold,
		TextSize = theme.TextSize + 2,
		TextColor3 = theme.Text,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextTruncate = Enum.TextTruncate.AtEnd,
		Parent = topBar,
	})

	if hasSubtitle then
		Create("TextLabel", {
			Name = "Subtitle",
			Position = UDim2.fromOffset(48, 25),
			Size = UDim2.new(1, -titleReserve, 0, 14),
			BackgroundTransparency = 1,
			Text = options.Subtitle,
			Font = theme.Font,
			TextSize = theme.TextSize - 2,
			TextColor3 = theme.TextDim,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextTruncate = Enum.TextTruncate.AtEnd,
			Parent = topBar,
		})
	end

	local closeButton = makeIconButton(topBar, theme, "Close", -10, theme.Error, { 45, -45 })
	local minimizeButton = makeIconButton(topBar, theme, "Minimize", -(10 + buttonSize + 4), theme.Accent, { 0 })

	closeButton.Activated:Connect(function()
		self:Destroy()
	end)

	minimizeButton.Activated:Connect(function()
		self:SetVisible(false)

		-- without a launcher button there would be no obvious way back
		if not self._launcher and self._toggleKey then
			self:Notify({
				Title = "Window hidden",
				Content = "Press " .. self._toggleKey.Name .. " to show it again.",
				Duration = 3,
			})
		end
	end)

	---- navigation (sidebar or tab strip) and pages -------------------------------------

	self._topDivider = Create("Frame", {
		Name = "TopDivider",
		Position = UDim2.fromOffset(0, topHeight),
		Size = UDim2.new(1, 0, 0, 1),
		BackgroundColor3 = theme.Stroke,
		BorderSizePixel = 0,
		Parent = self.Body,
	})

	self._navDivider = Create("Frame", {
		Name = "NavDivider",
		BackgroundColor3 = theme.Stroke,
		BorderSizePixel = 0,
		Parent = self.Body,
	})

	self._tabPadding = Create("UIPadding", {})
	self._tabLayout = Create("UIListLayout", {
		Padding = UDim.new(0, 4),
		SortOrder = Enum.SortOrder.LayoutOrder,
	})

	-- a ScrollingFrame, so any number of tabs still fits
	self.TabList = Create("ScrollingFrame", {
		Name = "TabList",
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		ScrollBarThickness = 0,
		CanvasSize = UDim2.new(),
		Parent = self.Body,
	}, {
		self._tabPadding,
		self._tabLayout,
	})

	self.Pages = Create("Frame", {
		Name = "Pages",
		BackgroundTransparency = 1,
		ClipsDescendants = true,
		Parent = self.Body,
	})

	self._notifications = Notification.new(self.Gui, theme)

	---- behaviour ----------------------------------------------------------------------

	table.insert(self._connections, Drag.attach(topBar, self.Main, {
		Clamp = function(position: UDim2)
			return self:_clampPosition(position)
		end,
	}))

	table.insert(self._connections, UserInputService.InputBegan:Connect(function(input, gameProcessed)
		if gameProcessed then
			return -- they're typing in chat or a textbox
		end
		if self._toggleKey and input.KeyCode == self._toggleKey then
			self:Toggle()
		end
	end))

	-- phone rotated, window resized, device emulator changed, ...
	table.insert(self._connections, self.Gui:GetPropertyChangedSignal("AbsoluteSize"):Connect(function()
		self:_layout()
	end))

	local wantLauncher = options.Launcher
	if wantLauncher == nil then
		wantLauncher = Device.isMobile()
	end
	if wantLauncher then
		self:_buildLauncher()
	end

	self:_layout()

	-- pop-in
	Tween.to(self._scale, { Scale = 1 }, 0.3, Enum.EasingStyle.Quint)

	return self
end

---- layout -------------------------------------------------------------------------------

-- Works out how big the window may be on this screen and switches between the sidebar layout
-- (wide) and the tab strip layout (narrow). Runs on creation and whenever the screen size changes.
function Window:_layout()
	local viewport = self.Gui.AbsoluteSize
	if viewport.X <= 0 or viewport.Y <= 0 then
		return
	end

	local wanted = self._sizeOption
	local width = wanted.X.Scale * viewport.X + wanted.X.Offset
	local height = wanted.Y.Scale * viewport.Y + wanted.Y.Offset

	width = math.max(math.min(width, viewport.X - SCREEN_MARGIN * 2), 240)
	local compact = width < COMPACT_WIDTH

	if compact then
		-- a phone in portrait is much taller than wide, so use that room
		height = math.max(height, 460)
	end
	height = math.max(math.min(height, viewport.Y - SCREEN_MARGIN * 2), 200)

	self._size = Vector2.new(width, height)
	self._compact = compact
	self.Main.Size = UDim2.fromOffset(width, height)

	local top = self._topbarHeight + 1

	if compact then
		self.TabList.Position = UDim2.fromOffset(0, top)
		self.TabList.Size = UDim2.new(1, 0, 0, TAB_STRIP_HEIGHT)
		self.TabList.CanvasSize = UDim2.new()
		self.TabList.AutomaticCanvasSize = Enum.AutomaticSize.X
		self.TabList.ScrollingDirection = Enum.ScrollingDirection.X

		self._tabLayout.FillDirection = Enum.FillDirection.Horizontal
		self._tabLayout.VerticalAlignment = Enum.VerticalAlignment.Center
		self._tabPadding.PaddingTop = UDim.new(0, 0)
		self._tabPadding.PaddingLeft = UDim.new(0, 8)
		self._tabPadding.PaddingRight = UDim.new(0, 8)

		self._navDivider.Position = UDim2.fromOffset(0, top + TAB_STRIP_HEIGHT)
		self._navDivider.Size = UDim2.new(1, 0, 0, 1)

		self.Pages.Position = UDim2.fromOffset(0, top + TAB_STRIP_HEIGHT + 1)
		self.Pages.Size = UDim2.new(1, 0, 1, -(top + TAB_STRIP_HEIGHT + 1))
	else
		self.TabList.Position = UDim2.fromOffset(0, top)
		self.TabList.Size = UDim2.new(0, SIDEBAR_WIDTH, 1, -top)
		self.TabList.CanvasSize = UDim2.new()
		self.TabList.AutomaticCanvasSize = Enum.AutomaticSize.Y
		self.TabList.ScrollingDirection = Enum.ScrollingDirection.Y

		self._tabLayout.FillDirection = Enum.FillDirection.Vertical
		self._tabLayout.VerticalAlignment = Enum.VerticalAlignment.Top
		self._tabPadding.PaddingTop = UDim.new(0, 10)
		self._tabPadding.PaddingLeft = UDim.new(0, 8)
		self._tabPadding.PaddingRight = UDim.new(0, 8)

		self._navDivider.Position = UDim2.fromOffset(SIDEBAR_WIDTH, top)
		self._navDivider.Size = UDim2.new(0, 1, 1, -top)

		self.Pages.Position = UDim2.fromOffset(SIDEBAR_WIDTH + 1, top)
		self.Pages.Size = UDim2.new(1, -(SIDEBAR_WIDTH + 1), 1, -top)
	end

	for _, tab in self.Tabs do
		tab:_setCompact(compact)
	end

	self._notifications:SetLayout(compact, viewport)
	self.Main.Position = self:_clampPosition(self.Main.Position)
end

-- Keeps the title bar on screen so the window can never be dragged somewhere it can't be
-- picked up again.
function Window:_clampPosition(position: UDim2): UDim2
	local viewport = self.Gui.AbsoluteSize
	local size = self._size
	local keep = 60 -- pixels of window that must stay visible horizontally

	local x = viewport.X * position.X.Scale + position.X.Offset
	local y = viewport.Y * position.Y.Scale + position.Y.Offset

	x = math.clamp(x, keep - size.X / 2, viewport.X - keep + size.X / 2)
	y = math.clamp(y, size.Y / 2, viewport.Y - 40 + size.Y / 2)

	return UDim2.new(
		position.X.Scale,
		x - viewport.X * position.X.Scale,
		position.Y.Scale,
		y - viewport.Y * position.Y.Scale
	)
end

-- The round button that shows/hides the window on devices without a toggle key.
function Window:_buildLauncher()
	local theme = self.Theme
	local size = 50

	local scale = Create("UIScale", { Scale = 1 })

	self._launcher = Create("Frame", {
		Name = "Launcher",
		Position = UDim2.new(0, 14, 0.4, 0),
		Size = UDim2.fromOffset(size, size),
		BackgroundColor3 = WHITE,
		BorderSizePixel = 0,
		Active = true,
		ZIndex = 5,
		Parent = self.Gui,
	}, {
		Create("UICorner", { CornerRadius = UDim.new(1, 0) }),
		Create("UIGradient", { Color = ColorSequence.new(theme.Accent, theme.Accent2), Rotation = 45 }),
		Create("UIStroke", { Color = WHITE, Transparency = 0.7, Thickness = 1.5, ApplyStrokeMode = Enum.ApplyStrokeMode.Border }),
		scale,
		Create("Frame", {
			AnchorPoint = Vector2.new(0.5, 0.5),
			Position = UDim2.fromScale(0.5, 0.5),
			Size = UDim2.fromOffset(18, 18),
			Rotation = 45,
			BackgroundColor3 = WHITE,
			BorderSizePixel = 0,
			ZIndex = 6,
		}, { Create("UICorner", { CornerRadius = UDim.new(0, 5) }) }),
	})

	Interact.bind(self._launcher, function(state)
		Tween.to(scale, { Scale = state == "Press" and 0.9 or 1 }, 0.1)
	end)

	table.insert(self._connections, Drag.attach(self._launcher, self._launcher, {
		OnTap = function()
			self:Toggle()
		end,
		Clamp = function(position: UDim2)
			local viewport = self.Gui.AbsoluteSize
			local x = viewport.X * position.X.Scale + position.X.Offset
			local y = viewport.Y * position.Y.Scale + position.Y.Offset

			return UDim2.fromOffset(
				math.clamp(x, 0, math.max(0, viewport.X - size)),
				math.clamp(y, 0, math.max(0, viewport.Y - size))
			)
		end,
	}))
end

---- tabs ---------------------------------------------------------------------------------

function Window:_selectTab(tab)
	if self._activeTab == tab then
		return
	end
	if self._activeTab then
		self._activeTab:_setActive(false)
	end

	self._activeTab = tab
	tab:_setActive(true)
end

function Window:AddTab(name: string)
	local tab = Tab.new(self, name)
	table.insert(self.Tabs, tab)

	-- first tab opens automatically so the window isn't empty
	if #self.Tabs == 1 then
		tab:Select()
	end

	return tab
end

---- public API ---------------------------------------------------------------------------

-- options: Title, Content, Duration (seconds, 0 = until tapped), Type = "Info" | "Success" | "Warning" | "Error"
function Window:Notify(options)
	self._notifications:Push(options or {})
end

function Window:SetTitle(title: string)
	self._titleLabel.Text = title
end

function Window:IsVisible(): boolean
	return self._visible
end

function Window:SetVisible(visible: boolean)
	if self._destroyed or visible == self._visible then
		return
	end
	self._visible = visible

	if visible then
		self._scale.Scale = HIDDEN_SCALE
		self.Main.Visible = true
		Tween.to(self._scale, { Scale = 1 }, 0.25, Enum.EasingStyle.Quint)
	else
		Tween.to(self._scale, { Scale = HIDDEN_SCALE }, 0.15).Completed:Connect(function()
			if not self._visible and not self._destroyed then
				self.Main.Visible = false
			end
		end)
	end
end

function Window:Toggle()
	self:SetVisible(not self._visible)
end

function Window:Destroy(fromGui: boolean?)
	if self._destroyed then
		return
	end
	self._destroyed = true

	self.Destroyed:Fire()
	self.Destroyed:Destroy()

	for _, connection in self._connections do
		connection:Disconnect()
	end
	table.clear(self._connections)

	Interact.release()

	-- when the ScreenGui is what started this, it is already on its way out
	if not fromGui then
		self.Gui:Destroy()
	end
end

return Window
end

-- Theme
sources[n_Theme] = function(script, require)
-- All colours and fonts live here so a custom theme is one table away.
--
--   Lumen.CreateWindow({ Preset = "Light" })
--   Lumen.CreateWindow({ Theme = { Accent = Color3.fromRGB(235, 90, 120) } })

local Theme = {}

Theme.Dark = {
	Background = Color3.fromRGB(17, 17, 23),
	Section = Color3.fromRGB(23, 23, 31),
	Surface = Color3.fromRGB(33, 33, 44),
	SurfaceHover = Color3.fromRGB(45, 45, 60),
	Stroke = Color3.fromRGB(54, 54, 71),

	-- Accent is used flat, Accent2 is the other end of the gradients
	Accent = Color3.fromRGB(104, 126, 255),
	Accent2 = Color3.fromRGB(168, 108, 255),

	Success = Color3.fromRGB(70, 206, 142),
	Warning = Color3.fromRGB(255, 187, 77),
	Error = Color3.fromRGB(255, 98, 116),

	Text = Color3.fromRGB(240, 240, 248),
	TextDim = Color3.fromRGB(144, 146, 170),

	Font = Enum.Font.GothamMedium,
	FontBold = Enum.Font.GothamBold,
	TextSize = 14,

	Corner = UDim.new(0, 8),
	WindowCorner = UDim.new(0, 14),
}

Theme.Light = {
	Background = Color3.fromRGB(246, 246, 250),
	Section = Color3.fromRGB(237, 237, 244),
	Surface = Color3.fromRGB(255, 255, 255),
	SurfaceHover = Color3.fromRGB(233, 233, 242),
	Stroke = Color3.fromRGB(208, 208, 222),

	Accent = Color3.fromRGB(78, 104, 240),
	Accent2 = Color3.fromRGB(148, 90, 240),

	Success = Color3.fromRGB(34, 170, 108),
	Warning = Color3.fromRGB(230, 150, 30),
	Error = Color3.fromRGB(226, 70, 90),

	Text = Color3.fromRGB(28, 28, 40),
	TextDim = Color3.fromRGB(104, 106, 128),

	Font = Enum.Font.GothamMedium,
	FontBold = Enum.Font.GothamBold,
	TextSize = 14,

	Corner = UDim.new(0, 8),
	WindowCorner = UDim.new(0, 14),
}

Theme.Presets = {
	Dark = Theme.Dark,
	Light = Theme.Light,
}

-- Copy a base theme and overwrite whatever the user passed in.
function Theme.extend(base, overrides)
	local result = table.clone(base)
	for key, value in overrides or {} do
		result[key] = value
	end
	return result
end

return Theme
end

-- Util/Create
sources[n_Util_Create] = function(script, require)
-- Tiny helper so we don't have to write Instance.new + 8 property lines every time.
--
--   Create("Frame", { Size = UDim2.fromScale(1, 1) }, {
--       Create("UICorner", { CornerRadius = UDim.new(0, 6) }),
--   })

local function Create(className: string, props: { [string]: any }?, children: { Instance }?): any
	local instance = Instance.new(className)
	local parent

	for key, value in props or {} do
		if key == "Parent" then
			-- set last, it's faster and avoids re-layout while we're still building
			parent = value
		else
			instance[key] = value
		end
	end

	for _, child in children or {} do
		child.Parent = instance
	end

	instance.Parent = parent
	return instance
end

return Create
end

-- Util/Device
sources[n_Util_Device] = function(script, require)
-- Tiny helpers for "am I on a phone?" decisions, so components can size themselves
-- for fingers instead of mouse cursors.

local UserInputService = game:GetService("UserInputService")

local Device = {}

-- Any touch screen (phones, tablets, touch laptops).
function Device.isTouch(): boolean
	return UserInputService.TouchEnabled
end

-- Touch screen and no physical keyboard: that's a phone or a tablet.
function Device.isMobile(): boolean
	return UserInputService.TouchEnabled and not UserInputService.KeyboardEnabled
end

-- Height of a normal row (button, toggle, ...). Fingers need about 44px, a mouse is fine with 36.
function Device.rowHeight(): number
	return UserInputService.TouchEnabled and 44 or 36
end

return Device
end

-- Util/Drag
sources[n_Util_Drag] = function(script, require)
-- Drag any GuiObject by a handle, with mouse or finger.
--
--   Drag.attach(topBar, window, {
--       Clamp = function(position: UDim2): UDim2 ... end,  -- keep it on screen
--       OnTap = function() ... end,                        -- released without moving
--       Threshold = 5,                                     -- pixels before it counts as a drag
--   })
--
-- Returns an object with :Disconnect().

local UserInputService = game:GetService("UserInputService")

local Drag = {}

local function isPointerDown(input: InputObject): boolean
	return input.UserInputType == Enum.UserInputType.MouseButton1
		or input.UserInputType == Enum.UserInputType.Touch
end

function Drag.attach(handle: GuiObject, target: GuiObject, options)
	options = options or {}
	local threshold = options.Threshold or 5

	local active = false
	local moved = false
	local startPoint = Vector3.zero
	local startPosition = target.Position

	local began = handle.InputBegan:Connect(function(input)
		if active or not isPointerDown(input) then
			return
		end

		active = true
		moved = false
		startPoint = input.Position
		startPosition = target.Position
	end)

	local changed = UserInputService.InputChanged:Connect(function(input)
		if not active then
			return
		end
		if input.UserInputType ~= Enum.UserInputType.MouseMovement and input.UserInputType ~= Enum.UserInputType.Touch then
			return
		end

		local delta = input.Position - startPoint
		if not moved then
			if delta.Magnitude < threshold then
				return -- still a tap, not a drag
			end
			moved = true
		end

		local position = UDim2.new(
			startPosition.X.Scale,
			startPosition.X.Offset + delta.X,
			startPosition.Y.Scale,
			startPosition.Y.Offset + delta.Y
		)

		if options.Clamp then
			position = options.Clamp(position)
		end
		target.Position = position
	end)

	local ended = UserInputService.InputEnded:Connect(function(input)
		if not active or not isPointerDown(input) then
			return
		end

		active = false
		if not moved and options.OnTap then
			options.OnTap()
		end
	end)

	local connection = {}

	function connection:Disconnect()
		began:Disconnect()
		changed:Disconnect()
		ended:Disconnect()
	end

	return connection
end

return Drag
end

-- Util/Interact
sources[n_Util_Interact] = function(script, require)
-- Hover / press states that behave on BOTH mouse and touch.
--
-- Plain MouseEnter / MouseLeave breaks on phones: a tap fires MouseEnter, but MouseLeave never
-- comes, so the row stays "hovered" forever. This helper only treats the mouse as hovering,
-- and releases the pressed state even when the finger slides off the button (or a
-- ScrollingFrame steals the touch and the button never sees InputEnded).
--
--   Interact.bind(button, function(state)  -- "Idle" | "Hover" | "Press"
--       ...
--   end)

local UserInputService = game:GetService("UserInputService")

local Interact = {}

local pressedResets = {} -- reset functions of everything that is currently held down
local globalConnection = nil
local references = 0

local function isPointer(input: InputObject): boolean
	return input.UserInputType == Enum.UserInputType.MouseButton1
		or input.UserInputType == Enum.UserInputType.Touch
end

-- Windows call retain() on creation and release() on destroy, so the one global
-- connection only exists while something is using it.
function Interact.retain()
	references += 1

	if not globalConnection then
		globalConnection = UserInputService.InputEnded:Connect(function(input)
			if not isPointer(input) then
				return
			end

			local resets = pressedResets
			pressedResets = {}
			for reset in resets do
				reset()
			end
		end)
	end
end

function Interact.release()
	references = math.max(0, references - 1)

	if references == 0 and globalConnection then
		globalConnection:Disconnect()
		globalConnection = nil
		table.clear(pressedResets)
	end
end

function Interact.bind(gui: GuiObject, callback: (state: string) -> ())
	local hovering = false
	local pressing = false
	local current = "Idle"

	local function refresh()
		local state = if pressing then "Press" elseif hovering then "Hover" else "Idle"
		if state ~= current then
			current = state
			callback(state)
		end
	end

	local function reset()
		pressing = false
		if UserInputService:GetLastInputType() == Enum.UserInputType.Touch then
			hovering = false
		end
		refresh()
	end

	gui.MouseEnter:Connect(function()
		hovering = UserInputService:GetLastInputType() ~= Enum.UserInputType.Touch
		refresh()
	end)

	gui.MouseLeave:Connect(function()
		hovering = false
		refresh()
	end)

	gui.InputBegan:Connect(function(input)
		if isPointer(input) then
			pressing = true
			pressedResets[reset] = true
			refresh()
		end
	end)

	gui.InputEnded:Connect(function(input)
		if isPointer(input) then
			pressedResets[reset] = nil
			reset()
		end
	end)
end

return Interact
end

-- Util/Signal
sources[n_Util_Signal] = function(script, require)
-- Minimal signal class. Not as fancy as GoodSignal, but it's tiny and does the job.

local Signal = {}
Signal.__index = Signal

function Signal.new()
	return setmetatable({ _handlers = {} }, Signal)
end

function Signal:Connect(fn)
	local handlers = self._handlers
	local handler = { Fn = fn }
	table.insert(handlers, handler)

	local connection = { Connected = true }

	function connection:Disconnect()
		if not self.Connected then
			return
		end
		self.Connected = false

		local index = table.find(handlers, handler)
		if index then
			table.remove(handlers, index)
		end
	end

	return connection
end

-- Runs the handler once, then disconnects itself.
function Signal:Once(fn)
	local connection
	connection = self:Connect(function(...)
		connection:Disconnect()
		fn(...)
	end)
	return connection
end

-- Yields until the signal fires, returns whatever it fired with.
function Signal:Wait()
	local thread = coroutine.running()
	self:Once(function(...)
		task.spawn(thread, ...)
	end)
	return coroutine.yield()
end

function Signal:Fire(...)
	-- clone first, a handler might disconnect itself while we're looping
	for _, handler in table.clone(self._handlers) do
		task.spawn(handler.Fn, ...)
	end
end

function Signal:Destroy()
	table.clear(self._handlers)
end

return Signal
end

-- Util/Tween
sources[n_Util_Tween] = function(script, require)
local TweenService = game:GetService("TweenService")

local Tween = {}

-- Fire and forget tween. Returns the tween in case you want to wait on it.
function Tween.to(instance: Instance, goal: { [string]: any }, duration: number?, style: Enum.EasingStyle?, direction: Enum.EasingDirection?)
	local info = TweenInfo.new(
		duration or 0.15,
		style or Enum.EasingStyle.Quart,
		direction or Enum.EasingDirection.Out
	)

	local tween = TweenService:Create(instance, info, goal)
	tween:Play()
	return tween
end

return Tween
end

-- init
sources[n_root] = function(script, require)
--[[
	Lumen UI
	A small, modular UI library for Roblox. Works with mouse, keyboard and touch.

	local Lumen = require(ReplicatedStorage.LumenUI)
	local window = Lumen.CreateWindow({ Title = "My Hub" })
	local tab = window:AddTab("Main")
	tab:AddButton({ Name = "Hello", Callback = function() print("hi") end })
]]

local Window = require(script.Core.Window)
local Theme = require(script.Theme)

local Lumen = {}

Lumen.Version = "0.2.0"
Lumen.Themes = Theme

function Lumen.CreateWindow(options)
	return Window.new(options)
end

return Lumen
end

return fakeRequire(n_root)
