#!/usr/bin/env python3
"""
Bundles src/ into single-file scripts for executors.

    python3 tools/bundle.py

Outputs (in executor/):
    LumenUI.bundle.lua   the library only      -> local Lumen = <paste/loadstring this>
    LumenUI.demo.lua     library + demo window -> paste straight into an executor
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT = ROOT / "executor"

EXTENSIONS = {".luau", ".lua"}


def var_name(parts):
    """Turn ('Core', 'Window') into a safe Lua variable name: n_Core_Window."""
    return "n_" + "_".join(re.sub(r"\W", "_", p) for p in parts) if parts else "n_root"


def collect():
    """Walk src/ and return (nodes, modules).

    nodes   -> list of (parts tuple) for every fake instance we need, parents first
    modules -> dict parts tuple -> source text
    """
    nodes = {(): True}
    modules = {}

    for path in sorted(SRC.rglob("*")):
        if path.suffix not in EXTENSIONS:
            continue

        rel = path.relative_to(SRC).with_suffix("")
        parts = tuple(rel.parts)

        # folders along the way become nodes too
        for i in range(1, len(parts)):
            nodes[parts[:i]] = True

        # init files belong to their folder (same rule Rojo uses)
        if parts[-1] == "init":
            parts = parts[:-1]
        else:
            nodes[parts] = True

        modules[parts] = path.read_text(encoding="utf-8")

    ordered = sorted(nodes, key=lambda p: (len(p), p))
    return ordered, modules


def build_library():
    nodes, modules = collect()
    lines = []
    add = lines.append

    add("-- Lumen UI single-file bundle (generated by tools/bundle.py, do not edit by hand)")
    add("local Node = {}")
    add("-- anything that isn't a real field (Name / Parent) is looked up as a child,")
    add("-- which is what makes `script.Parent.Util.Create` work")
    add("Node.__index = function(self, key)")
    add('\treturn rawget(self, "_children")[key]')
    add("end")
    add("")
    add("local function newNode(name, parent)")
    add('\tlocal node = setmetatable({ Name = name, Parent = parent, _children = {} }, Node)')
    add("\tif parent then")
    add("\t\tparent._children[name] = node")
    add("\tend")
    add("\treturn node")
    add("end")
    add("")
    add("local sources = {}")
    add("local cache = {}")
    add("")
    add("local function fakeRequire(node)")
    add("\tif cache[node] == nil then")
    add("\t\tcache[node] = sources[node](node, fakeRequire)")
    add("\tend")
    add("\treturn cache[node]")
    add("end")
    add("")

    for parts in nodes:
        if not parts:
            add('local n_root = newNode("LumenUI")')
        else:
            add(f'local {var_name(parts)} = newNode("{parts[-1]}", {var_name(parts[:-1])})')

    add("")

    # each file becomes a function that has its own `script` and `require`
    for parts, source in modules.items():
        label = "/".join(parts) if parts else "init"
        add(f"-- {label}")
        add(f"sources[{var_name(parts)}] = function(script, require)")
        add(source.rstrip())
        add("end")
        add("")

    add("return fakeRequire(n_root)")
    add("")
    return "\n".join(lines)


def build_demo(library):
    demo = (OUT / "demo_body.lua").read_text(encoding="utf-8")
    return (
        "-- Lumen UI: library + demo in one file. Paste the whole thing into your executor.\n"
        "local Lumen = (function()\n"
        f"{library}\n"
        "end)()\n\n"
        f"{demo}"
    )


def main():
    OUT.mkdir(exist_ok=True)

    library = build_library()
    (OUT / "LumenUI.bundle.lua").write_text(library, encoding="utf-8")
    (OUT / "LumenUI.demo.lua").write_text(build_demo(library), encoding="utf-8")

    print(f"wrote {OUT / 'LumenUI.bundle.lua'} ({len(library.splitlines())} lines)")
    print(f"wrote {OUT / 'LumenUI.demo.lua'}")


if __name__ == "__main__":
    main()
